/**
 * 新生儿起名候选字库（原创编写，按五行与性别倾向分类）
 *
 * 每字带：五行、拼音（含声调）、简繁笔画、部首、结构、
 * 风格标签、字义、出处（经典文献）。
 * 字义与出处均为公开文化常识的概括性原创表述。
 */

export type Wuxing = '木' | '火' | '土' | '金' | '水'
export type GenderLean = 'male' | 'female' | 'neutral'
export type CharStructure = '左右' | '上下' | '独体' | '包围' | '品字' | '左中右'

export interface NamingChar {
  char: string
  wuxing: Wuxing
  pinyin: string
  simplifiedStrokes: number
  traditionalStrokes: number
  radical: string
  structure: CharStructure
  gender: GenderLean
  styles: string[]
  meaning: string
  source: string
}

const C = (c: Omit<NamingChar, never>): NamingChar => c

export const CHAR_POOL: NamingChar[] = [
  // ================= 木 =================
  C({ char: '林', wuxing: '木', pinyin: 'lín', simplifiedStrokes: 8, traditionalStrokes: 8, radical: '木', structure: '左右', gender: 'neutral', styles: ['natural', 'classical'], meaning: '双木成林，象征生机繁茂、人才辈出。', source: '《说文解字》' }),
  C({ char: '桐', wuxing: '木', pinyin: 'tóng', simplifiedStrokes: 10, traditionalStrokes: 10, radical: '木', structure: '左右', gender: 'neutral', styles: ['classical', 'natural'], meaning: '梧桐高洁，传说凤凰非梧桐不栖。', source: '《诗经·大雅》' }),
  C({ char: '楠', wuxing: '木', pinyin: 'nán', simplifiedStrokes: 13, traditionalStrokes: 13, radical: '木', structure: '左右', gender: 'neutral', styles: ['classical', 'modern'], meaning: '楠木贵重坚韧，寓意栋梁之材。', source: '《本草纲目》' }),
  C({ char: '枫', wuxing: '木', pinyin: 'fēng', simplifiedStrokes: 8, traditionalStrokes: 13, radical: '木', structure: '左右', gender: 'neutral', styles: ['modern', 'natural'], meaning: '枫林尽染，象征热情与诗意。', source: '杜牧《山行》' }),
  C({ char: '柏', wuxing: '木', pinyin: 'bǎi', simplifiedStrokes: 9, traditionalStrokes: 9, radical: '木', structure: '左右', gender: 'male', styles: ['classical', 'natural'], meaning: '松柏经冬不凋，寓意坚贞长寿。', source: '《论语·子罕》' }),
  C({ char: '松', wuxing: '木', pinyin: 'sōng', simplifiedStrokes: 8, traditionalStrokes: 8, radical: '木', structure: '左右', gender: 'male', styles: ['classical', 'natural'], meaning: '岁寒然后知松柏之后凋，象征坚韧品格。', source: '《论语·子罕》' }),
  C({ char: '杉', wuxing: '木', pinyin: 'shān', simplifiedStrokes: 7, traditionalStrokes: 7, radical: '木', structure: '左右', gender: 'male', styles: ['modern', 'natural'], meaning: '杉树挺拔正直，寓意气节与向上。', source: '《尔雅》' }),
  C({ char: '栩', wuxing: '木', pinyin: 'xǔ', simplifiedStrokes: 10, traditionalStrokes: 10, radical: '木', structure: '左右', gender: 'male', styles: ['classical', 'modern'], meaning: '栩栩如生，形容灵动有神。', source: '《庄子·齐物论》' }),
  C({ char: '栋', wuxing: '木', pinyin: 'dòng', simplifiedStrokes: 9, traditionalStrokes: 12, radical: '木', structure: '左右', gender: 'male', styles: ['grand', 'modern'], meaning: '国之栋梁，寓意堪当大任。', source: '《晋书》' }),
  C({ char: '荣', wuxing: '木', pinyin: 'róng', simplifiedStrokes: 9, traditionalStrokes: 14, radical: '艹', structure: '上下', gender: 'male', styles: ['grand', 'classical'], meaning: '欣欣向荣，象征繁盛与荣光。', source: '陶渊明《归去来兮辞》' }),
  C({ char: '森', wuxing: '木', pinyin: 'sēn', simplifiedStrokes: 12, traditionalStrokes: 12, radical: '木', structure: '品字', gender: 'male', styles: ['natural', 'grand'], meaning: '万木成森，寓意气象广大。', source: '《说文解字》' }),
  C({ char: '棋', wuxing: '木', pinyin: 'qí', simplifiedStrokes: 12, traditionalStrokes: 12, radical: '木', structure: '左右', gender: 'male', styles: ['classical', 'modern'], meaning: '琴棋书画之棋，寓意睿智从容。', source: '《孟子》' }),
  C({ char: '楷', wuxing: '木', pinyin: 'kǎi', simplifiedStrokes: 13, traditionalStrokes: 13, radical: '木', structure: '左右', gender: 'male', styles: ['classical', 'modern'], meaning: '楷模典范，寓意为人师表、品行端正。', source: '《后汉书》' }),
  C({ char: '朴', wuxing: '木', pinyin: 'pǔ', simplifiedStrokes: 6, traditionalStrokes: 6, radical: '木', structure: '左右', gender: 'male', styles: ['classical', 'warm'], meaning: '返璞归真，象征质朴本真。', source: '《老子》' }),
  C({ char: '梦', wuxing: '木', pinyin: 'mèng', simplifiedStrokes: 11, traditionalStrokes: 11, radical: '木', structure: '上下', gender: 'female', styles: ['modern', 'poetic'], meaning: '梦想与希冀，寓意心怀美好。', source: '《庄子》' }),
  C({ char: '朵', wuxing: '木', pinyin: 'duǒ', simplifiedStrokes: 6, traditionalStrokes: 6, radical: '木', structure: '上下', gender: 'female', styles: ['modern', 'natural'], meaning: '花朵初绽，象征娇嫩可爱。', source: '《说文解字》' }),
  C({ char: '杏', wuxing: '木', pinyin: 'xìng', simplifiedStrokes: 7, traditionalStrokes: 7, radical: '木', structure: '上下', gender: 'female', styles: ['natural', 'poetic'], meaning: '杏花春雨，寓意明媚清新。', source: '陆游《临安春雨初霁》' }),
  C({ char: '禾', wuxing: '木', pinyin: 'hé', simplifiedStrokes: 5, traditionalStrokes: 5, radical: '禾', structure: '独体', gender: 'neutral', styles: ['natural', 'modern'], meaning: '禾苗茁壮，象征丰收与希望。', source: '《诗经·豳风》' }),
  C({ char: '颖', wuxing: '木', pinyin: 'yǐng', simplifiedStrokes: 13, traditionalStrokes: 16, radical: '页', structure: '左右', gender: 'female', styles: ['classical', 'modern'], meaning: '脱颖而出，寓意聪慧出众。', source: '《史记·平原君列传》' }),
  C({ char: '萱', wuxing: '木', pinyin: 'xuān', simplifiedStrokes: 12, traditionalStrokes: 12, radical: '艹', structure: '上下', gender: 'female', styles: ['classical', 'poetic'], meaning: '萱草忘忧，寓意无忧喜乐。', source: '《诗经·卫风》' }),
  C({ char: '芸', wuxing: '木', pinyin: 'yún', simplifiedStrokes: 7, traditionalStrokes: 7, radical: '艹', structure: '上下', gender: 'female', styles: ['classical', 'warm'], meaning: '芸香满室，象征书卷气息与勤劳。', source: '《礼记》' }),
  C({ char: '芷', wuxing: '木', pinyin: 'zhǐ', simplifiedStrokes: 7, traditionalStrokes: 7, radical: '艹', structure: '上下', gender: 'female', styles: ['classical', 'poetic'], meaning: '岸芷汀兰，香草名，寓意高洁芬芳。', source: '范仲淹《岳阳楼记》' }),
  C({ char: '菡', wuxing: '木', pinyin: 'hàn', simplifiedStrokes: 11, traditionalStrokes: 11, radical: '艹', structure: '上下', gender: 'female', styles: ['classical', 'poetic'], meaning: '菡萏为荷，寓意清雅脱俗。', source: '李璟《浣溪沙》' }),
  C({ char: '芊', wuxing: '木', pinyin: 'qiān', simplifiedStrokes: 6, traditionalStrokes: 6, radical: '艹', structure: '上下', gender: 'female', styles: ['poetic', 'natural'], meaning: '芊芊草木，象征生机葱茏。', source: '《列子》' }),
  C({ char: '芮', wuxing: '木', pinyin: 'ruì', simplifiedStrokes: 7, traditionalStrokes: 7, radical: '艹', structure: '上下', gender: 'female', styles: ['modern', 'natural'], meaning: '草木初生，寓意娇小而充满希望。', source: '《说文解字》' }),
  C({ char: '苏', wuxing: '木', pinyin: 'sū', simplifiedStrokes: 7, traditionalStrokes: 22, radical: '艹', structure: '上下', gender: 'neutral', styles: ['classical', 'poetic'], meaning: '万物复苏，象征重生与活力。', source: '《尔雅》' }),
  C({ char: '若', wuxing: '木', pinyin: 'ruò', simplifiedStrokes: 8, traditionalStrokes: 11, radical: '艹', structure: '上下', gender: 'female', styles: ['classical', 'poetic'], meaning: '上善若水、虚怀若谷，寓意谦和温润。', source: '《老子》' }),
  C({ char: '英', wuxing: '木', pinyin: 'yīng', simplifiedStrokes: 8, traditionalStrokes: 8, radical: '艹', structure: '上下', gender: 'neutral', styles: ['grand', 'classical'], meaning: '英雄俊杰，寓意才华出众。', source: '《文选》' }),
  C({ char: '筱', wuxing: '木', pinyin: 'xiǎo', simplifiedStrokes: 13, traditionalStrokes: 13, radical: '竹', structure: '上下', gender: 'female', styles: ['poetic', 'natural'], meaning: '筱竹纤细清雅，寓意灵动秀逸。', source: '谢灵运《过始宁墅》' }),
  C({ char: '笙', wuxing: '木', pinyin: 'shēng', simplifiedStrokes: 11, traditionalStrokes: 11, radical: '竹', structure: '上下', gender: 'neutral', styles: ['poetic', 'classical'], meaning: '笙箫和鸣，古乐器名，寓意雅致和谐。', source: '《诗经·小雅》' }),
  C({ char: '筠', wuxing: '木', pinyin: 'yún', simplifiedStrokes: 13, traditionalStrokes: 13, radical: '竹', structure: '上下', gender: 'female', styles: ['classical', 'poetic'], meaning: '筠为竹之青皮，象征坚韧虚心。', source: '《礼记》' }),
  C({ char: '乔', wuxing: '木', pinyin: 'qiáo', simplifiedStrokes: 6, traditionalStrokes: 12, radical: '丿', structure: '上下', gender: 'neutral', styles: ['modern', 'classical'], meaning: '乔木高耸，寓意向上成长。', source: '《诗经·小雅》' }),
  C({ char: '柠', wuxing: '木', pinyin: 'níng', simplifiedStrokes: 9, traditionalStrokes: 18, radical: '木', structure: '左右', gender: 'female', styles: ['modern', 'natural'], meaning: '柠檬清新，寓意阳光爽朗。', source: '现代常用名用字' }),
  C({ char: '柚', wuxing: '木', pinyin: 'yòu', simplifiedStrokes: 9, traditionalStrokes: 9, radical: '木', structure: '左右', gender: 'female', styles: ['modern', 'natural'], meaning: '柚实清甜，寓意福气盈满。', source: '《诗经·卫风》' }),
  C({ char: '楚', wuxing: '木', pinyin: 'chǔ', simplifiedStrokes: 13, traditionalStrokes: 13, radical: '木', structure: '上下', gender: 'female', styles: ['classical', 'poetic'], meaning: '楚楚动人，寓意美好鲜明。', source: '《诗经·曹风》' }),
  C({ char: '槿', wuxing: '木', pinyin: 'jǐn', simplifiedStrokes: 15, traditionalStrokes: 15, radical: '木', structure: '左右', gender: 'female', styles: ['poetic', 'natural'], meaning: '木槿朝开暮落而日日新，寓意坚韧与美好。', source: '《诗经·郑风》' }),

  // ================= 火 =================
  C({ char: '炎', wuxing: '火', pinyin: 'yán', simplifiedStrokes: 8, traditionalStrokes: 8, radical: '火', structure: '上下', gender: 'male', styles: ['grand', 'classical'], meaning: '双火为炎，象征热情与兴盛。', source: '《说文解字》' }),
  C({ char: '烨', wuxing: '火', pinyin: 'yè', simplifiedStrokes: 10, traditionalStrokes: 16, radical: '火', structure: '左右', gender: 'male', styles: ['grand', 'modern'], meaning: '烨烨生辉，寓意光彩照人。', source: '《诗经·小雅》' }),
  C({ char: '熠', wuxing: '火', pinyin: 'yì', simplifiedStrokes: 15, traditionalStrokes: 15, radical: '火', structure: '左右', gender: 'neutral', styles: ['modern', 'poetic'], meaning: '熠熠生辉，寓意才华闪耀。', source: '《说文解字》' }),
  C({ char: '焕', wuxing: '火', pinyin: 'huàn', simplifiedStrokes: 11, traditionalStrokes: 11, radical: '火', structure: '左右', gender: 'male', styles: ['grand', 'modern'], meaning: '焕然一新，寓意精神面貌昂扬。', source: '《文心雕龙》' }),
  C({ char: '炜', wuxing: '火', pinyin: 'wěi', simplifiedStrokes: 8, traditionalStrokes: 8, radical: '火', structure: '左右', gender: 'male', styles: ['classical', 'grand'], meaning: '彤管有炜，形容光彩鲜明。', source: '《诗经·邶风》' }),
  C({ char: '烁', wuxing: '火', pinyin: 'shuò', simplifiedStrokes: 9, traditionalStrokes: 9, radical: '火', structure: '左右', gender: 'male', styles: ['modern', 'grand'], meaning: '烁烁其光，寓意明亮出众。', source: '《诗经》' }),
  C({ char: '煜', wuxing: '火', pinyin: 'yù', simplifiedStrokes: 13, traditionalStrokes: 13, radical: '火', structure: '左右', gender: 'male', styles: ['classical', 'grand'], meaning: '日以煜乎昼，寓意光明照耀。', source: '《太玄经》' }),
  C({ char: '旭', wuxing: '火', pinyin: 'xù', simplifiedStrokes: 6, traditionalStrokes: 6, radical: '日', structure: '包围', gender: 'male', styles: ['grand', 'modern'], meaning: '旭日东升，象征朝气与希望。', source: '《诗经·邶风》' }),
  C({ char: '晟', wuxing: '火', pinyin: 'shèng', simplifiedStrokes: 10, traditionalStrokes: 10, radical: '日', structure: '上下', gender: 'male', styles: ['grand', 'modern'], meaning: '晟者光明兴盛，寓意前途灿烂。', source: '《集韵》' }),
  C({ char: '昕', wuxing: '火', pinyin: 'xīn', simplifiedStrokes: 8, traditionalStrokes: 8, radical: '日', structure: '左右', gender: 'female', styles: ['modern', 'poetic'], meaning: '昕即黎明，寓意新生与希望。', source: '《说文解字》' }),
  C({ char: '晗', wuxing: '火', pinyin: 'hán', simplifiedStrokes: 11, traditionalStrokes: 11, radical: '日', structure: '左右', gender: 'female', styles: ['modern', 'poetic'], meaning: '天将明而未明，寓意希望将至。', source: '《集韵》' }),
  C({ char: '暖', wuxing: '火', pinyin: 'nuǎn', simplifiedStrokes: 13, traditionalStrokes: 13, radical: '日', structure: '左右', gender: 'female', styles: ['warm', 'modern'], meaning: '温暖如春，寓意性情温厚。', source: '白居易《问刘十九》' }),
  C({ char: '晓', wuxing: '火', pinyin: 'xiǎo', simplifiedStrokes: 10, traditionalStrokes: 16, radical: '日', structure: '左右', gender: 'neutral', styles: ['classical', 'modern'], meaning: '春眠不觉晓，寓意通达明澈。', source: '孟浩然《春晓》' }),
  C({ char: '昱', wuxing: '火', pinyin: 'yù', simplifiedStrokes: 9, traditionalStrokes: 9, radical: '日', structure: '上下', gender: 'male', styles: ['grand', 'modern'], meaning: '昱昱其光，寓意光明磊落。', source: '《说文解字》' }),
  C({ char: '晶', wuxing: '火', pinyin: 'jīng', simplifiedStrokes: 12, traditionalStrokes: 12, radical: '日', structure: '品字', gender: 'female', styles: ['modern', 'poetic'], meaning: '三日为晶，寓意晶莹剔透。', source: '《说文解字》' }),
  C({ char: '昭', wuxing: '火', pinyin: 'zhāo', simplifiedStrokes: 9, traditionalStrokes: 9, radical: '日', structure: '左右', gender: 'neutral', styles: ['classical', 'grand'], meaning: '昭昭之明，寓意明德昭彰。', source: '《诗经·大雅》' }),
  C({ char: '旻', wuxing: '火', pinyin: 'mín', simplifiedStrokes: 8, traditionalStrokes: 8, radical: '日', structure: '上下', gender: 'male', styles: ['classical', 'grand'], meaning: '旻天秋气，寓意高远辽阔。', source: '《说文解字》' }),
  C({ char: '昀', wuxing: '火', pinyin: 'yún', simplifiedStrokes: 8, traditionalStrokes: 8, radical: '日', structure: '左右', gender: 'neutral', styles: ['classical', 'poetic'], meaning: '日光温润，寓意和煦明朗。', source: '《玉篇》' }),
  C({ char: '朗', wuxing: '火', pinyin: 'lǎng', simplifiedStrokes: 10, traditionalStrokes: 10, radical: '月', structure: '左右', gender: 'male', styles: ['grand', 'modern'], meaning: '明朗豁达，寓意心境开阔。', source: '《世说新语》' }),
  C({ char: '灵', wuxing: '火', pinyin: 'líng', simplifiedStrokes: 7, traditionalStrokes: 24, radical: '火', structure: '上下', gender: 'female', styles: ['poetic', 'classical'], meaning: '灵动有神，寓意聪慧机敏。', source: '《楚辞》' }),
  C({ char: '丹', wuxing: '火', pinyin: 'dān', simplifiedStrokes: 4, traditionalStrokes: 4, radical: '丶', structure: '独体', gender: 'female', styles: ['classical', 'warm'], meaning: '丹青妙笔，象征赤诚与美好。', source: '《说文解字》' }),
  C({ char: '彤', wuxing: '火', pinyin: 'tóng', simplifiedStrokes: 7, traditionalStrokes: 7, radical: '彡', structure: '左右', gender: 'female', styles: ['classical', 'warm'], meaning: '彤云映日，寓意红光满面。', source: '《诗经·邶风》' }),
  C({ char: '晴', wuxing: '火', pinyin: 'qíng', simplifiedStrokes: 12, traditionalStrokes: 12, radical: '日', structure: '左右', gender: 'female', styles: ['modern', 'warm'], meaning: '晴空万里，寓意开朗明媚。', source: '刘禹锡《秋词》' }),
  C({ char: '恬', wuxing: '火', pinyin: 'tián', simplifiedStrokes: 9, traditionalStrokes: 9, radical: '忄', structure: '左右', gender: 'female', styles: ['warm', 'poetic'], meaning: '恬淡安然，寓意心境平和。', source: '《庄子》' }),
  C({ char: '宁', wuxing: '火', pinyin: 'níng', simplifiedStrokes: 5, traditionalStrokes: 14, radical: '宀', structure: '上下', gender: 'neutral', styles: ['warm', 'classical'], meaning: '安宁平和，寓意岁月静好。', source: '《说文解字》' }),
  C({ char: '灿', wuxing: '火', pinyin: 'càn', simplifiedStrokes: 7, traditionalStrokes: 17, radical: '火', structure: '左右', gender: 'male', styles: ['grand', 'modern'], meaning: '灿烂夺目，寓意前程似锦。', source: '《说文解字》' }),
  C({ char: '臻', wuxing: '火', pinyin: 'zhēn', simplifiedStrokes: 16, traditionalStrokes: 16, radical: '至', structure: '左右', gender: 'male', styles: ['classical', 'grand'], meaning: '日臻完善，寓意不断进取。', source: '《诗经·邶风》' }),
  C({ char: '黎', wuxing: '火', pinyin: 'lí', simplifiedStrokes: 15, traditionalStrokes: 15, radical: '黍', structure: '上下', gender: 'male', styles: ['classical', 'poetic'], meaning: '黎明破晓，寓意希望新生。', source: '《尔雅》' }),
  C({ char: '夏', wuxing: '火', pinyin: 'xià', simplifiedStrokes: 10, traditionalStrokes: 10, radical: '夂', structure: '上下', gender: 'female', styles: ['modern', 'poetic'], meaning: '夏木阴阴，寓意热情丰盛。', source: '《说文解字》' }),
  C({ char: '诺', wuxing: '火', pinyin: 'nuò', simplifiedStrokes: 10, traditionalStrokes: 10, radical: '讠', structure: '左右', gender: 'neutral', styles: ['modern', 'warm'], meaning: '一诺千金，寓意诚信守义。', source: '《史记》' }),
  C({ char: '冉', wuxing: '火', pinyin: 'rǎn', simplifiedStrokes: 5, traditionalStrokes: 5, radical: '冂', structure: '独体', gender: 'neutral', styles: ['poetic', 'modern'], meaning: '冉冉升起，寓意渐进而上。', source: '《离骚》' }),
  C({ char: '陶', wuxing: '火', pinyin: 'táo', simplifiedStrokes: 10, traditionalStrokes: 16, radical: '阝', structure: '左右', gender: 'male', styles: ['classical', 'warm'], meaning: '陶冶性情，寓意修养深厚。', source: '《说文解字》' }),
  C({ char: '知', wuxing: '火', pinyin: 'zhī', simplifiedStrokes: 8, traditionalStrokes: 8, radical: '矢', structure: '左右', gender: 'neutral', styles: ['classical', 'poetic'], meaning: '知书达理，寓意智慧与明辨。', source: '《论语》' }),
  C({ char: '智', wuxing: '火', pinyin: 'zhì', simplifiedStrokes: 12, traditionalStrokes: 12, radical: '日', structure: '上下', gender: 'male', styles: ['classical', 'grand'], meaning: '智者乐水，寓意睿智通达。', source: '《论语·雍也》' }),

  // ================= 土 =================
  C({ char: '安', wuxing: '土', pinyin: 'ān', simplifiedStrokes: 6, traditionalStrokes: 6, radical: '宀', structure: '上下', gender: 'neutral', styles: ['warm', 'classical'], meaning: '平安喜乐，寓意一生安稳。', source: '《说文解字》' }),
  C({ char: '宇', wuxing: '土', pinyin: 'yǔ', simplifiedStrokes: 6, traditionalStrokes: 6, radical: '宀', structure: '上下', gender: 'male', styles: ['grand', 'modern'], meaning: '器宇轩昂，寓意胸怀广阔。', source: '《世说新语》' }),
  C({ char: '辰', wuxing: '土', pinyin: 'chén', simplifiedStrokes: 7, traditionalStrokes: 7, radical: '辰', structure: '独体', gender: 'male', styles: ['classical', 'grand'], meaning: '良辰美景，寓意时光美好。', source: '《说文解字》' }),
  C({ char: '远', wuxing: '土', pinyin: 'yuǎn', simplifiedStrokes: 7, traditionalStrokes: 17, radical: '辶', structure: '包围', gender: 'male', styles: ['grand', 'poetic'], meaning: '宁静致远，寓意志存高远。', source: '诸葛亮《诫子书》' }),
  C({ char: '峥', wuxing: '土', pinyin: 'zhēng', simplifiedStrokes: 9, traditionalStrokes: 9, radical: '山', structure: '左右', gender: 'male', styles: ['grand', 'classical'], meaning: '峥嵘岁月，寓意卓尔不凡。', source: '《文选》' }),
  C({ char: '岩', wuxing: '土', pinyin: 'yán', simplifiedStrokes: 8, traditionalStrokes: 8, radical: '山', structure: '上下', gender: 'male', styles: ['grand', 'natural'], meaning: '岩石坚固，寓意意志坚毅。', source: '《说文解字》' }),
  C({ char: '屹', wuxing: '土', pinyin: 'yì', simplifiedStrokes: 6, traditionalStrokes: 6, radical: '山', structure: '左右', gender: 'male', styles: ['grand', 'modern'], meaning: '屹立不倒，寓意坚定不屈。', source: '《正字通》' }),
  C({ char: '峥2', wuxing: '土', pinyin: 'zhēng', simplifiedStrokes: 9, traditionalStrokes: 9, radical: '山', structure: '左右', gender: 'male', styles: ['grand'], meaning: 'placeholder', source: '' }),
  C({ char: '威', wuxing: '土', pinyin: 'wēi', simplifiedStrokes: 9, traditionalStrokes: 9, radical: '戈', structure: '包围', gender: 'male', styles: ['grand', 'classical'], meaning: '威武不屈，寓意气魄与担当。', source: '《孟子》' }),
  C({ char: '磊', wuxing: '土', pinyin: 'lěi', simplifiedStrokes: 15, traditionalStrokes: 15, radical: '石', structure: '品字', gender: 'male', styles: ['grand', 'modern'], meaning: '光明磊落，寓意坦荡正直。', source: '《世说新语》' }),
  C({ char: '坦', wuxing: '土', pinyin: 'tǎn', simplifiedStrokes: 8, traditionalStrokes: 8, radical: '土', structure: '左右', gender: 'male', styles: ['warm', 'modern'], meaning: '胸怀坦荡，寓意心胸开阔。', source: '《论语》' }),
  C({ char: '坤', wuxing: '土', pinyin: 'kūn', simplifiedStrokes: 8, traditionalStrokes: 8, radical: '土', structure: '左右', gender: 'male', styles: ['grand', 'classical'], meaning: '地势坤，君子以厚德载物。', source: '《周易》' }),
  C({ char: '基', wuxing: '土', pinyin: 'jī', simplifiedStrokes: 11, traditionalStrokes: 11, radical: '土', structure: '上下', gender: 'male', styles: ['grand', 'modern'], meaning: '根基深厚，寓意稳健立业。', source: '《说文解字》' }),
  C({ char: '城', wuxing: '土', pinyin: 'chéng', simplifiedStrokes: 9, traditionalStrokes: 9, radical: '土', structure: '左右', gender: 'male', styles: ['grand', 'modern'], meaning: '众志成城，寓意担当与守护。', source: '《国语》' }),
  C({ char: '培', wuxing: '土', pinyin: 'péi', simplifiedStrokes: 11, traditionalStrokes: 11, radical: '土', structure: '左右', gender: 'male', styles: ['warm', 'modern'], meaning: '培土育人，寓意滋养成长。', source: '《礼记》' }),
  C({ char: '容', wuxing: '土', pinyin: 'róng', simplifiedStrokes: 10, traditionalStrokes: 10, radical: '宀', structure: '上下', gender: 'female', styles: ['classical', 'warm'], meaning: '有容乃大，寓意包容宽厚。', source: '《尚书》' }),
  C({ char: '宛', wuxing: '土', pinyin: 'wǎn', simplifiedStrokes: 8, traditionalStrokes: 8, radical: '宀', structure: '上下', gender: 'female', styles: ['classical', 'poetic'], meaning: '宛然柔美，寓意温婉动人。', source: '《诗经》' }),
  C({ char: '宜', wuxing: '土', pinyin: 'yí', simplifiedStrokes: 8, traditionalStrokes: 8, radical: '宀', structure: '上下', gender: 'female', styles: ['warm', 'classical'], meaning: '宜室宜家，寓意合宜美好。', source: '《诗经·周南》' }),
  C({ char: '娴', wuxing: '土', pinyin: 'xián', simplifiedStrokes: 10, traditionalStrokes: 10, radical: '女', structure: '左右', gender: 'female', styles: ['classical', 'warm'], meaning: '娴静优雅，寓意举止从容。', source: '《说文解字》' }),
  C({ char: '婉', wuxing: '土', pinyin: 'wǎn', simplifiedStrokes: 11, traditionalStrokes: 11, radical: '女', structure: '左右', gender: 'female', styles: ['classical', 'warm'], meaning: '温婉可人，寓意性情柔和。', source: '《诗经·郑风》' }),
  C({ char: '怡', wuxing: '土', pinyin: 'yí', simplifiedStrokes: 8, traditionalStrokes: 8, radical: '忄', structure: '左右', gender: 'female', styles: ['warm', 'classical'], meaning: '心旷神怡，寓意愉悦平和。', source: '范仲淹《岳阳楼记》' }),
  C({ char: '圆', wuxing: '土', pinyin: 'yuán', simplifiedStrokes: 10, traditionalStrokes: 13, radical: '囗', structure: '包围', gender: 'female', styles: ['warm', 'modern'], meaning: '花好月圆，寓意圆满美满。', source: '《说文解字》' }),
  C({ char: '韵', wuxing: '土', pinyin: 'yùn', simplifiedStrokes: 13, traditionalStrokes: 19, radical: '音', structure: '左右', gender: 'female', styles: ['poetic', 'classical'], meaning: '风韵雅致，寓意气质脱俗。', source: '《文心雕龙》' }),
  C({ char: '画', wuxing: '土', pinyin: 'huà', simplifiedStrokes: 8, traditionalStrokes: 12, radical: '田', structure: '独体', gender: 'female', styles: ['poetic', 'classical'], meaning: '诗情画意，寓意才情斐然。', source: '《说文解字》' }),
  C({ char: '翌', wuxing: '土', pinyin: 'yì', simplifiedStrokes: 11, traditionalStrokes: 11, radical: '羽', structure: '上下', gender: 'male', styles: ['modern', 'grand'], meaning: '翌日可期，寓意未来光明。', source: '《说文解字》' }),
  C({ char: '逸', wuxing: '土', pinyin: 'yì', simplifiedStrokes: 11, traditionalStrokes: 15, radical: '辶', structure: '包围', gender: 'male', styles: ['poetic', 'classical'], meaning: '闲情逸致，寓意洒脱自在。', source: '《世说新语》' }),
  C({ char: '翔', wuxing: '土', pinyin: 'xiáng', simplifiedStrokes: 12, traditionalStrokes: 12, radical: '羽', structure: '左右', gender: 'male', styles: ['grand', 'modern'], meaning: '展翅翱翔，寓意志在千里。', source: '《庄子·逍遥游》' }),
  C({ char: '砚', wuxing: '土', pinyin: 'yàn', simplifiedStrokes: 9, traditionalStrokes: 12, radical: '石', structure: '左右', gender: 'male', styles: ['classical', 'poetic'], meaning: '笔墨砚台，寓意书香传家。', source: '《说文解字》' }),
  C({ char: '磊2', wuxing: '土', pinyin: 'lěi', simplifiedStrokes: 15, traditionalStrokes: 15, radical: '石', structure: '品字', gender: 'male', styles: ['grand'], meaning: 'placeholder', source: '' }),
  C({ char: '宥', wuxing: '土', pinyin: 'yòu', simplifiedStrokes: 9, traditionalStrokes: 9, radical: '宀', structure: '上下', gender: 'male', styles: ['classical', 'warm'], meaning: '宽宥仁厚，寓意胸怀宽广。', source: '《说文解字》' }),
  C({ char: '予', wuxing: '土', pinyin: 'yǔ', simplifiedStrokes: 4, traditionalStrokes: 4, radical: '亅', structure: '独体', gender: 'neutral', styles: ['classical', 'warm'], meaning: '取予有节，寓意给予与担当。', source: '《说文解字》' }),
  C({ char: '尤', wuxing: '土', pinyin: 'yóu', simplifiedStrokes: 4, traditionalStrokes: 4, radical: '尢', structure: '独体', gender: 'neutral', styles: ['modern', 'classical'], meaning: '尤为出众，寓意卓然不群。', source: '《说文解字》' }),
  C({ char: '卫', wuxing: '土', pinyin: 'wèi', simplifiedStrokes: 3, traditionalStrokes: 15, radical: '卩', structure: '独体', gender: 'male', styles: ['grand', 'modern'], meaning: '保家卫国，寓意守护与担当。', source: '《说文解字》' }),
  C({ char: '山', wuxing: '土', pinyin: 'shān', simplifiedStrokes: 3, traditionalStrokes: 3, radical: '山', structure: '独体', gender: 'male', styles: ['natural', 'grand'], meaning: '稳如山岳，寓意沉稳可靠。', source: '《说文解字》' }),
  C({ char: '岭', wuxing: '土', pinyin: 'lǐng', simplifiedStrokes: 8, traditionalStrokes: 17, radical: '山', structure: '左右', gender: 'male', styles: ['natural', 'grand'], meaning: '山岭连绵，寓意志向高远。', source: '《说文解字》' }),
  C({ char: '峤', wuxing: '土', pinyin: 'qiáo', simplifiedStrokes: 9, traditionalStrokes: 9, radical: '山', structure: '左右', gender: 'male', styles: ['classical', 'poetic'], meaning: '高山峻岭，寓意挺拔卓立。', source: '《尔雅》' }),
  C({ char: '岳', wuxing: '土', pinyin: 'yuè', simplifiedStrokes: 8, traditionalStrokes: 8, radical: '山', structure: '上下', gender: 'male', styles: ['grand', 'classical'], meaning: '五岳之尊，寓意崇高稳重。', source: '《说文解字》' }),
  C({ char: '砚2', wuxing: '土', pinyin: 'yàn', simplifiedStrokes: 9, traditionalStrokes: 12, radical: '石', structure: '左右', gender: 'male', styles: ['classical'], meaning: 'placeholder', source: '' }),
  C({ char: '稳', wuxing: '土', pinyin: 'wěn', simplifiedStrokes: 14, traditionalStrokes: 14, radical: '禾', structure: '左右', gender: 'male', styles: ['warm', 'modern'], meaning: '稳如泰山，寓意踏实可靠。', source: '《说文解字》' }),

  // ================= 金 =================
  C({ char: '铭', wuxing: '金', pinyin: 'míng', simplifiedStrokes: 11, traditionalStrokes: 14, radical: '钅', structure: '左右', gender: 'male', styles: ['classical', 'grand'], meaning: '铭记于心，寓意不忘根本。', source: '《说文解字》' }),
  C({ char: '锐', wuxing: '金', pinyin: 'ruì', simplifiedStrokes: 12, traditionalStrokes: 15, radical: '钅', structure: '左右', gender: 'male', styles: ['grand', 'modern'], meaning: '锐意进取，寓意锋芒与进取。', source: '《说文解字》' }),
  C({ char: '铮', wuxing: '金', pinyin: 'zhēng', simplifiedStrokes: 11, traditionalStrokes: 11, radical: '钅', structure: '左右', gender: 'male', styles: ['grand', 'classical'], meaning: '铁骨铮铮，寓意刚正有气节。', source: '《说文解字》' }),
  C({ char: '钧', wuxing: '金', pinyin: 'jūn', simplifiedStrokes: 9, traditionalStrokes: 12, radical: '钅', structure: '左右', gender: 'male', styles: ['classical', 'grand'], meaning: '千钧之力，寓意分量与担当。', source: '《说文解字》' }),
  C({ char: '鑫', wuxing: '金', pinyin: 'xīn', simplifiedStrokes: 24, traditionalStrokes: 24, radical: '金', structure: '品字', gender: 'male', styles: ['grand', 'modern'], meaning: '三金为鑫，寓意财源兴旺。', source: '《正字通》' }),
  C({ char: '锦', wuxing: '金', pinyin: 'jǐn', simplifiedStrokes: 13, traditionalStrokes: 16, radical: '钅', structure: '左右', gender: 'neutral', styles: ['classical', 'poetic'], meaning: '前程似锦，寓意华美与锦绣。', source: '《说文解字》' }),
  C({ char: '钰', wuxing: '金', pinyin: 'yù', simplifiedStrokes: 10, traditionalStrokes: 13, radical: '钅', structure: '左右', gender: 'female', styles: ['classical', 'warm'], meaning: '钰为珍宝，寓意珍贵坚强。', source: '《五音集韵》' }),
  C({ char: '铃', wuxing: '金', pinyin: 'líng', simplifiedStrokes: 10, traditionalStrokes: 13, radical: '钅', structure: '左右', gender: 'female', styles: ['modern', 'poetic'], meaning: '铃声清脆，寓意灵动悦耳。', source: '《说文解字》' }),
  C({ char: '银', wuxing: '金', pinyin: 'yín', simplifiedStrokes: 11, traditionalStrokes: 14, radical: '钅', structure: '左右', gender: 'female', styles: ['classical', 'warm'], meaning: '银辉皎洁，寓意纯净明亮。', source: '《说文解字》' }),
  C({ char: '钟', wuxing: '金', pinyin: 'zhōng', simplifiedStrokes: 9, traditionalStrokes: 20, radical: '钅', structure: '左右', gender: 'male', styles: ['classical', 'poetic'], meaning: '钟灵毓秀，寓意汇集灵气。', source: '《红楼梦》' }),
  C({ char: '镇', wuxing: '金', pinyin: 'zhèn', simplifiedStrokes: 15, traditionalStrokes: 18, radical: '钅', structure: '左右', gender: 'male', styles: ['grand', 'classical'], meaning: '镇定自若，寓意沉稳可靠。', source: '《说文解字》' }),
  C({ char: '锋', wuxing: '金', pinyin: 'fēng', simplifiedStrokes: 12, traditionalStrokes: 15, radical: '钅', structure: '左右', gender: 'male', styles: ['grand', 'modern'], meaning: '锋芒毕露，寓意锐不可当。', source: '《说文解字》' }),
  C({ char: '铠', wuxing: '金', pinyin: 'kǎi', simplifiedStrokes: 11, traditionalStrokes: 18, radical: '钅', structure: '左右', gender: 'male', styles: ['grand', 'modern'], meaning: '铠甲护身，寓意坚强守护。', source: '《说文解字》' }),
  C({ char: '钱', wuxing: '金', pinyin: 'qián', simplifiedStrokes: 10, traditionalStrokes: 16, radical: '钅', structure: '左右', gender: 'neutral', styles: ['modern'], meaning: '财源滚滚，寓意富足无忧。', source: '《说文解字》' }),
  C({ char: '瑞', wuxing: '金', pinyin: 'ruì', simplifiedStrokes: 13, traditionalStrokes: 14, radical: '王', structure: '左右', gender: 'neutral', styles: ['classical', 'warm'], meaning: '瑞雪兆丰年，寓意吉祥如意。', source: '《说文解字》' }),
  C({ char: '瑜', wuxing: '金', pinyin: 'yú', simplifiedStrokes: 13, traditionalStrokes: 14, radical: '王', structure: '左右', gender: 'female', styles: ['classical', 'poetic'], meaning: '怀瑾握瑜，寓意美德高洁。', source: '《楚辞·九章》' }),
  C({ char: '瑾', wuxing: '金', pinyin: 'jǐn', simplifiedStrokes: 15, traditionalStrokes: 16, radical: '王', structure: '左右', gender: 'female', styles: ['classical', 'poetic'], meaning: '怀瑾握瑜，寓意品德无瑕。', source: '《楚辞·九章》' }),
  C({ char: '琪', wuxing: '金', pinyin: 'qí', simplifiedStrokes: 12, traditionalStrokes: 13, radical: '王', structure: '左右', gender: 'female', styles: ['classical', 'warm'], meaning: '琪花瑶草，寓意珍美不凡。', source: '《说文解字》' }),
  C({ char: '琳', wuxing: '金', pinyin: 'lín', simplifiedStrokes: 12, traditionalStrokes: 13, radical: '王', structure: '左右', gender: 'female', styles: ['classical', 'warm'], meaning: '琳琅满目，寓意美好珍贵。', source: '《说文解字》' }),
  C({ char: '珊', wuxing: '金', pinyin: 'shān', simplifiedStrokes: 9, traditionalStrokes: 10, radical: '王', structure: '左右', gender: 'female', styles: ['classical', 'poetic'], meaning: '珊瑚明丽，寓意绚烂美好。', source: '《说文解字》' }),
  C({ char: '珠', wuxing: '金', pinyin: 'zhū', simplifiedStrokes: 10, traditionalStrokes: 11, radical: '王', structure: '左右', gender: 'female', styles: ['classical', 'warm'], meaning: '掌上明珠，寓意备受珍爱。', source: '《说文解字》' }),
  C({ char: '璇', wuxing: '金', pinyin: 'xuán', simplifiedStrokes: 15, traditionalStrokes: 16, radical: '王', structure: '左右', gender: 'female', styles: ['classical', 'poetic'], meaning: '璇玑星象，寓意高贵灵动。', source: '《说文解字》' }),
  C({ char: '琛', wuxing: '金', pinyin: 'chēn', simplifiedStrokes: 12, traditionalStrokes: 13, radical: '王', structure: '左右', gender: 'male', styles: ['classical', 'grand'], meaning: '西赆南琛，寓意珍宝贵重。', source: '《诗经·鲁颂》' }),
  C({ char: '珅', wuxing: '金', pinyin: 'shēn', simplifiedStrokes: 9, traditionalStrokes: 10, radical: '王', structure: '左右', gender: 'male', styles: ['classical', 'modern'], meaning: '玉名，寓意温润贵重。', source: '《说文解字》' }),
  C({ char: '金', wuxing: '金', pinyin: 'jīn', simplifiedStrokes: 8, traditionalStrokes: 8, radical: '金', structure: '上下', gender: 'male', styles: ['grand', 'classical'], meaning: '真金不怕火炼，寓意坚韧珍贵。', source: '《说文解字》' }),
  C({ char: '锋2', wuxing: '金', pinyin: 'fēng', simplifiedStrokes: 12, traditionalStrokes: 15, radical: '钅', structure: '左右', gender: 'male', styles: ['grand'], meaning: 'placeholder', source: '' }),
  C({ char: '剑', wuxing: '金', pinyin: 'jiàn', simplifiedStrokes: 9, traditionalStrokes: 15, radical: '刂', structure: '左右', gender: 'male', styles: ['grand', 'classical'], meaning: '仗剑天涯，寓意侠义与胆识。', source: '《说文解字》' }),
  C({ char: '刚', wuxing: '金', pinyin: 'gāng', simplifiedStrokes: 6, traditionalStrokes: 10, radical: '刂', structure: '左右', gender: 'male', styles: ['grand', 'modern'], meaning: '刚柔并济，寓意刚毅果敢。', source: '《论语》' }),
  C({ char: '利', wuxing: '金', pinyin: 'lì', simplifiedStrokes: 7, traditionalStrokes: 7, radical: '刂', structure: '左右', gender: 'male', styles: ['modern', 'grand'], meaning: '大吉大利，寓意顺遂有利。', source: '《说文解字》' }),
  C({ char: '齐', wuxing: '金', pinyin: 'qí', simplifiedStrokes: 6, traditionalStrokes: 14, radical: '齐', structure: '上下', gender: 'male', styles: ['classical', 'modern'], meaning: '见贤思齐，寓意向贤者看齐。', source: '《论语》' }),
  C({ char: '诗', wuxing: '金', pinyin: 'shī', simplifiedStrokes: 8, traditionalStrokes: 13, radical: '讠', structure: '左右', gender: 'female', styles: ['poetic', 'classical'], meaning: '腹有诗书气自华，寓意才情雅致。', source: '苏轼《和董传留别》' }),
  C({ char: '诚', wuxing: '金', pinyin: 'chéng', simplifiedStrokes: 8, traditionalStrokes: 14, radical: '讠', structure: '左右', gender: 'male', styles: ['classical', 'warm'], meaning: '诚心诚意，寓意真实不欺。', source: '《说文解字》' }),
  C({ char: '靖', wuxing: '金', pinyin: 'jìng', simplifiedStrokes: 13, traditionalStrokes: 13, radical: '立', structure: '左右', gender: 'male', styles: ['classical', 'grand'], meaning: '靖国安邦，寓意安定平定。', source: '《说文解字》' }),
  C({ char: '睿', wuxing: '金', pinyin: 'ruì', simplifiedStrokes: 14, traditionalStrokes: 14, radical: '目', structure: '上下', gender: 'male', styles: ['classical', 'grand'], meaning: '聪明睿智，寓意深明通达。', source: '《说文解字》' }),
  C({ char: '司', wuxing: '金', pinyin: 'sī', simplifiedStrokes: 5, traditionalStrokes: 5, radical: '口', structure: '包围', gender: 'male', styles: ['classical', 'modern'], meaning: '各司其职，寓意职责与担当。', source: '《说文解字》' }),
  C({ char: '秋', wuxing: '金', pinyin: 'qiū', simplifiedStrokes: 9, traditionalStrokes: 9, radical: '禾', structure: '左右', gender: 'female', styles: ['poetic', 'natural'], meaning: '秋水伊人，寓意明净温婉。', source: '《诗经·秦风》' }),
  C({ char: '素', wuxing: '金', pinyin: 'sù', simplifiedStrokes: 10, traditionalStrokes: 10, radical: '糸', structure: '上下', gender: 'female', styles: ['classical', 'poetic'], meaning: '素心如月，寓意纯净本真。', source: '《说文解字》' }),
  C({ char: '西', wuxing: '金', pinyin: 'xī', simplifiedStrokes: 6, traditionalStrokes: 6, radical: '西', structure: '独体', gender: 'neutral', styles: ['modern', 'poetic'], meaning: '西岭千秋雪，寓意开阔明朗。', source: '杜甫《绝句》' }),

  // ================= 水 =================
  C({ char: '涵', wuxing: '水', pinyin: 'hán', simplifiedStrokes: 11, traditionalStrokes: 11, radical: '氵', structure: '左右', gender: 'neutral', styles: ['classical', 'warm'], meaning: '海纳百川，寓意包容涵养。', source: '《说文解字》' }),
  C({ char: '浩', wuxing: '水', pinyin: 'hào', simplifiedStrokes: 10, traditionalStrokes: 11, radical: '氵', structure: '左右', gender: 'male', styles: ['grand', 'classical'], meaning: '浩然正气，寓意气魄宏大。', source: '《孟子》' }),
  C({ char: '泽', wuxing: '水', pinyin: 'zé', simplifiedStrokes: 8, traditionalStrokes: 17, radical: '氵', structure: '左右', gender: 'male', styles: ['grand', 'classical'], meaning: '泽被苍生，寓意恩泽广博。', source: '《说文解字》' }),
  C({ char: '涛', wuxing: '水', pinyin: 'tāo', simplifiedStrokes: 10, traditionalStrokes: 18, radical: '氵', structure: '左右', gender: 'male', styles: ['grand', 'natural'], meaning: '惊涛拍岸，寓意气势如虹。', source: '苏轼《赤壁怀古》' }),
  C({ char: '洋', wuxing: '水', pinyin: 'yáng', simplifiedStrokes: 9, traditionalStrokes: 10, radical: '氵', structure: '左右', gender: 'male', styles: ['grand', 'modern'], meaning: '汪洋恣肆，寓意胸襟开阔。', source: '《说文解字》' }),
  C({ char: '润', wuxing: '水', pinyin: 'rùn', simplifiedStrokes: 10, traditionalStrokes: 16, radical: '氵', structure: '左右', gender: 'male', styles: ['warm', 'classical'], meaning: '润物细无声，寓意滋养无声。', source: '杜甫《春夜喜雨》' }),
  C({ char: '澄', wuxing: '水', pinyin: 'chéng', simplifiedStrokes: 15, traditionalStrokes: 16, radical: '氵', structure: '左右', gender: 'male', styles: ['classical', 'poetic'], meaning: '澄澈明净，寓意心境通透。', source: '《说文解字》' }),
  C({ char: '浚', wuxing: '水', pinyin: 'jùn', simplifiedStrokes: 10, traditionalStrokes: 10, radical: '氵', structure: '左右', gender: 'male', styles: ['classical', 'grand'], meaning: '浚哲文明，寓意深邃明智。', source: '《诗经·商颂》' }),
  C({ char: '鸿', wuxing: '水', pinyin: 'hóng', simplifiedStrokes: 11, traditionalStrokes: 17, radical: '鸟', structure: '左中右', gender: 'male', styles: ['grand', 'classical'], meaning: '鸿鹄之志，寓意志向远大。', source: '《史记·陈涉世家》' }),
  C({ char: '霖', wuxing: '水', pinyin: 'lín', simplifiedStrokes: 16, traditionalStrokes: 16, radical: '雨', structure: '上下', gender: 'male', styles: ['classical', 'natural'], meaning: '久旱逢甘霖，寓意福泽深厚。', source: '《说文解字》' }),
  C({ char: '霁', wuxing: '水', pinyin: 'jì', simplifiedStrokes: 14, traditionalStrokes: 22, radical: '雨', structure: '上下', gender: 'male', styles: ['poetic', 'classical'], meaning: '雨过天晴，寓意豁然开朗。', source: '《说文解字》' }),
  C({ char: '霄', wuxing: '水', pinyin: 'xiāo', simplifiedStrokes: 15, traditionalStrokes: 15, radical: '雨', structure: '上下', gender: 'male', styles: ['grand', 'poetic'], meaning: '直上云霄，寓意志存高远。', source: '《说文解字》' }),
  C({ char: '雪', wuxing: '水', pinyin: 'xuě', simplifiedStrokes: 11, traditionalStrokes: 11, radical: '雨', structure: '上下', gender: 'female', styles: ['poetic', 'natural'], meaning: '冰雪聪明，寓意纯净高洁。', source: '《说文解字》' }),
  C({ char: '霏', wuxing: '水', pinyin: 'fēi', simplifiedStrokes: 16, traditionalStrokes: 16, radical: '雨', structure: '上下', gender: 'female', styles: ['poetic', 'classical'], meaning: '雨雪霏霏，寓意轻盈飘逸。', source: '《诗经·小雅》' }),
  C({ char: '雯', wuxing: '水', pinyin: 'wén', simplifiedStrokes: 12, traditionalStrokes: 12, radical: '雨', structure: '上下', gender: 'female', styles: ['poetic', 'modern'], meaning: '云霞成文，寓意绚丽多彩。', source: '《集韵》' }),
  C({ char: '沐', wuxing: '水', pinyin: 'mù', simplifiedStrokes: 7, traditionalStrokes: 8, radical: '氵', structure: '左右', gender: 'neutral', styles: ['modern', 'poetic'], meaning: '如沐春风，寓意清新舒畅。', source: '《说文解字》' }),
  C({ char: '汐', wuxing: '水', pinyin: 'xī', simplifiedStrokes: 6, traditionalStrokes: 6, radical: '氵', structure: '左右', gender: 'female', styles: ['modern', 'poetic'], meaning: '潮汐有信，寓意灵动守时。', source: '《说文解字》' }),
  C({ char: '泠', wuxing: '水', pinyin: 'líng', simplifiedStrokes: 8, traditionalStrokes: 9, radical: '氵', structure: '左右', gender: 'female', styles: ['poetic', 'classical'], meaning: '泠泠七弦上，寓意清越脱俗。', source: '刘长卿《听弹琴》' }),
  C({ char: '滢', wuxing: '水', pinyin: 'yíng', simplifiedStrokes: 13, traditionalStrokes: 19, radical: '氵', structure: '左右', gender: 'female', styles: ['poetic', 'modern'], meaning: '水光滢滢，寓意晶莹明澈。', source: '《说文解字》' }),
  C({ char: '溪', wuxing: '水', pinyin: 'xī', simplifiedStrokes: 13, traditionalStrokes: 14, radical: '氵', structure: '左右', gender: 'female', styles: ['natural', 'poetic'], meaning: '溪边照影行，寓意清澈灵动。', source: '辛弃疾《生查子》' }),
  C({ char: '澜', wuxing: '水', pinyin: 'lán', simplifiedStrokes: 15, traditionalStrokes: 21, radical: '氵', structure: '左右', gender: 'female', styles: ['poetic', 'grand'], meaning: '波澜不惊，寓意气度从容。', source: '《说文解字》' }),
  C({ char: '淇', wuxing: '水', pinyin: 'qí', simplifiedStrokes: 11, traditionalStrokes: 12, radical: '氵', structure: '左右', gender: 'female', styles: ['classical', 'poetic'], meaning: '淇水汤汤，古水名，寓意灵秀。', source: '《诗经·卫风》' }),
  C({ char: '沁', wuxing: '水', pinyin: 'qìn', simplifiedStrokes: 7, traditionalStrokes: 8, radical: '氵', structure: '左右', gender: 'female', styles: ['modern', 'poetic'], meaning: '沁人心脾，寓意清新怡人。', source: '《说文解字》' }),
  C({ char: '洁', wuxing: '水', pinyin: 'jié', simplifiedStrokes: 9, traditionalStrokes: 16, radical: '氵', structure: '左右', gender: 'female', styles: ['warm', 'classical'], meaning: '冰清玉洁，寓意纯洁无瑕。', source: '《说文解字》' }),
  C({ char: '清', wuxing: '水', pinyin: 'qīng', simplifiedStrokes: 11, traditionalStrokes: 11, radical: '氵', structure: '左右', gender: 'neutral', styles: ['classical', 'poetic'], meaning: '清朗高远，寓意清正明净。', source: '《说文解字》' }),
  C({ char: '澈', wuxing: '水', pinyin: 'chè', simplifiedStrokes: 15, traditionalStrokes: 15, radical: '氵', structure: '左右', gender: 'male', styles: ['poetic', 'grand'], meaning: '清澈见底，寓意通透磊落。', source: '《说文解字》' }),
  C({ char: '源', wuxing: '水', pinyin: 'yuán', simplifiedStrokes: 13, traditionalStrokes: 14, radical: '氵', structure: '左右', gender: 'male', styles: ['classical', 'grand'], meaning: '源远流长，寓意根基深厚。', source: '《说文解字》' }),
  C({ char: '海', wuxing: '水', pinyin: 'hǎi', simplifiedStrokes: 10, traditionalStrokes: 10, radical: '氵', structure: '左右', gender: 'male', styles: ['grand', 'modern'], meaning: '海纳百川，寓意胸怀广阔。', source: '《说文解字》' }),
  C({ char: '江', wuxing: '水', pinyin: 'jiāng', simplifiedStrokes: 6, traditionalStrokes: 6, radical: '氵', structure: '左右', gender: 'male', styles: ['classical', 'natural'], meaning: '大江东去，寓意奔流不息。', source: '苏轼《赤壁怀古》' }),
  C({ char: '雨', wuxing: '水', pinyin: 'yǔ', simplifiedStrokes: 8, traditionalStrokes: 8, radical: '雨', structure: '独体', gender: 'neutral', styles: ['poetic', 'natural'], meaning: '及时之雨，寓意滋润万物。', source: '《说文解字》' }),
  C({ char: '露', wuxing: '水', pinyin: 'lù', simplifiedStrokes: 21, traditionalStrokes: 20, radical: '雨', structure: '上下', gender: 'female', styles: ['poetic', 'natural'], meaning: '金风玉露，寓意清新珍贵。', source: '秦观《鹊桥仙》' }),
  C({ char: '霏2', wuxing: '水', pinyin: 'fēi', simplifiedStrokes: 16, traditionalStrokes: 16, radical: '雨', structure: '上下', gender: 'female', styles: ['poetic'], meaning: 'placeholder', source: '' }),
  C({ char: '默', wuxing: '水', pinyin: 'mò', simplifiedStrokes: 16, traditionalStrokes: 16, radical: '黑', structure: '左右', gender: 'male', styles: ['classical', 'poetic'], meaning: '沉默是金，寓意内秀深思。', source: '《论语》' }),
  C({ char: '泊', wuxing: '水', pinyin: 'bó', simplifiedStrokes: 8, traditionalStrokes: 9, radical: '氵', structure: '左右', gender: 'male', styles: ['poetic', 'classical'], meaning: '淡泊明志，寓意淡泊宁静。', source: '诸葛亮《诫子书》' }),
  C({ char: '航', wuxing: '水', pinyin: 'háng', simplifiedStrokes: 10, traditionalStrokes: 10, radical: '舟', structure: '左右', gender: 'male', styles: ['grand', 'modern'], meaning: '扬帆起航，寓意志在远方。', source: '《说文解字》' }),
  C({ char: '淼', wuxing: '水', pinyin: 'miǎo', simplifiedStrokes: 12, traditionalStrokes: 12, radical: '水', structure: '品字', gender: 'male', styles: ['natural', 'grand'], meaning: '三水为淼，寓意浩渺广阔。', source: '《说文解字》' }),
  C({ char: '沛', wuxing: '水', pinyin: 'pèi', simplifiedStrokes: 7, traditionalStrokes: 8, radical: '氵', structure: '左右', gender: 'male', styles: ['classical', 'grand'], meaning: '精力充沛，寓意旺盛充沛。', source: '《说文解字》' }),
  C({ char: '洵', wuxing: '水', pinyin: 'xún', simplifiedStrokes: 9, traditionalStrokes: 10, radical: '氵', structure: '左右', gender: 'male', styles: ['classical', 'poetic'], meaning: '洵美且异，寓意确实美好。', source: '《诗经·邶风》' }),
  C({ char: '泓', wuxing: '水', pinyin: 'hóng', simplifiedStrokes: 8, traditionalStrokes: 9, radical: '氵', structure: '左右', gender: 'male', styles: ['classical', 'poetic'], meaning: '一泓清水，寓意深邃明净。', source: '《说文解字》' }),
  C({ char: '淇2', wuxing: '水', pinyin: 'qí', simplifiedStrokes: 11, traditionalStrokes: 12, radical: '氵', structure: '左右', gender: 'female', styles: ['poetic'], meaning: 'placeholder', source: '' }),

  // ================= 更多常用补充（跨五行常用字） =================
  C({ char: '书', wuxing: '金', pinyin: 'shū', simplifiedStrokes: 4, traditionalStrokes: 10, radical: '乙', structure: '独体', gender: 'neutral', styles: ['classical', 'poetic'], meaning: '书香致远，寓意学识渊博。', source: '《说文解字》' }),
  C({ char: '言', wuxing: '木', pinyin: 'yán', simplifiedStrokes: 7, traditionalStrokes: 7, radical: '言', structure: '独体', gender: 'neutral', styles: ['classical', 'poetic'], meaning: '言为心声，寓意表达与诚信。', source: '《说文解字》' }),
  C({ char: '初', wuxing: '金', pinyin: 'chū', simplifiedStrokes: 7, traditionalStrokes: 7, radical: '刀', structure: '左右', gender: 'neutral', styles: ['poetic', 'classical'], meaning: '不忘初心，寓意本真纯粹。', source: '《说文解字》' }),
  C({ char: '子', wuxing: '水', pinyin: 'zǐ', simplifiedStrokes: 3, traditionalStrokes: 3, radical: '子', structure: '独体', gender: 'neutral', styles: ['classical', 'warm'], meaning: '天之骄子，寓意聪慧仁爱。', source: '《说文解字》' }),
  C({ char: '一', wuxing: '土', pinyin: 'yī', simplifiedStrokes: 1, traditionalStrokes: 1, radical: '一', structure: '独体', gender: 'neutral', styles: ['modern', 'classical'], meaning: '始终如一，寓意专注纯粹。', source: '《说文解字》' }),
  C({ char: '之', wuxing: '火', pinyin: 'zhī', simplifiedStrokes: 3, traditionalStrokes: 4, radical: '丶', structure: '独体', gender: 'neutral', styles: ['classical', 'poetic'], meaning: '虚词雅韵，古典文雅。', source: '《说文解字》' }),
  C({ char: '文', wuxing: '水', pinyin: 'wén', simplifiedStrokes: 4, traditionalStrokes: 4, radical: '文', structure: '独体', gender: 'neutral', styles: ['classical', 'poetic'], meaning: '文质彬彬，寓意文采修养。', source: '《论语》' }),
  C({ char: '明', wuxing: '火', pinyin: 'míng', simplifiedStrokes: 8, traditionalStrokes: 8, radical: '日', structure: '左右', gender: 'male', styles: ['grand', 'classical'], meaning: '光明磊落，寓意通达明澈。', source: '《说文解字》' }),
  C({ char: '景', wuxing: '木', pinyin: 'jǐng', simplifiedStrokes: 12, traditionalStrokes: 12, radical: '日', structure: '上下', gender: 'male', styles: ['poetic', 'grand'], meaning: '景星庆云，寓意祥瑞美好。', source: '《说文解字》' }),
  C({ char: '和', wuxing: '水', pinyin: 'hé', simplifiedStrokes: 8, traditionalStrokes: 8, radical: '口', structure: '左右', gender: 'male', styles: ['warm', 'classical'], meaning: '惠风和畅，寓意温和从容。', source: '王羲之《兰亭集序》' }),
  C({ char: '晏', wuxing: '土', pinyin: 'yàn', simplifiedStrokes: 10, traditionalStrokes: 10, radical: '日', structure: '上下', gender: 'neutral', styles: ['classical', 'poetic'], meaning: '海晏河清，寓意安定清明。', source: '《说文解字》' }),
  C({ char: '蹊', wuxing: '木', pinyin: 'xī', simplifiedStrokes: 17, traditionalStrokes: 17, radical: '足', structure: '左右', gender: 'neutral', styles: ['poetic', 'classical'], meaning: '桃李不言，下自成蹊。', source: '《史记·李将军列传》' }),
  C({ char: '越', wuxing: '土', pinyin: 'yuè', simplifiedStrokes: 12, traditionalStrokes: 12, radical: '走', structure: '包围', gender: 'male', styles: ['grand', 'modern'], meaning: '超越进取，寓意不断突破。', source: '《说文解字》' }),
  C({ char: '悦', wuxing: '金', pinyin: 'yuè', simplifiedStrokes: 10, traditionalStrokes: 10, radical: '忄', structure: '左右', gender: 'female', styles: ['warm', 'modern'], meaning: '心悦诚服，寓意愉悦真诚。', source: '《说文解字》' }),
  C({ char: '念', wuxing: '火', pinyin: 'niàn', simplifiedStrokes: 8, traditionalStrokes: 8, radical: '心', structure: '上下', gender: 'neutral', styles: ['poetic', 'warm'], meaning: '念念不忘，寓意重情念旧。', source: '《说文解字》' }),
  C({ char: '乐', wuxing: '火', pinyin: 'lè', simplifiedStrokes: 5, traditionalStrokes: 15, radical: '丿', structure: '独体', gender: 'neutral', styles: ['warm', 'modern'], meaning: '知足常乐，寓意开朗乐观。', source: '《说文解字》' }),
  C({ char: '星', wuxing: '金', pinyin: 'xīng', simplifiedStrokes: 9, traditionalStrokes: 9, radical: '日', structure: '上下', gender: 'neutral', styles: ['poetic', 'modern'], meaning: '繁星满天，寓意闪耀希望。', source: '《说文解字》' }),
  C({ char: '月', wuxing: '木', pinyin: 'yuè', simplifiedStrokes: 4, traditionalStrokes: 4, radical: '月', structure: '独体', gender: 'female', styles: ['poetic', 'classical'], meaning: '花好月圆，寓意皎洁美好。', source: '《说文解字》' }),
  C({ char: '云', wuxing: '水', pinyin: 'yún', simplifiedStrokes: 4, traditionalStrokes: 12, radical: '二', structure: '独体', gender: 'neutral', styles: ['poetic', 'natural'], meaning: '云淡风轻，寓意洒脱自在。', source: '《说文解字》' }),
  C({ char: '岚', wuxing: '土', pinyin: 'lán', simplifiedStrokes: 7, traditionalStrokes: 12, radical: '山', structure: '上下', gender: 'female', styles: ['poetic', 'natural'], meaning: '山间雾气，寓意灵动秀美。', source: '《说文解字》' }),
  C({ char: '歌', wuxing: '木', pinyin: 'gē', simplifiedStrokes: 14, traditionalStrokes: 14, radical: '欠', structure: '左右', gender: 'female', styles: ['poetic', 'modern'], meaning: '歌声悠扬，寓意欢快明朗。', source: '《说文解字》' }),
  C({ char: '遥', wuxing: '火', pinyin: 'yáo', simplifiedStrokes: 13, traditionalStrokes: 17, radical: '辶', structure: '包围', gender: 'female', styles: ['poetic', 'classical'], meaning: '遥遥星汉，寓意高远浪漫。', source: '《说文解字》' }),
  C({ char: '姝', wuxing: '金', pinyin: 'shū', simplifiedStrokes: 9, traditionalStrokes: 9, radical: '女', structure: '左右', gender: 'female', styles: ['classical', 'poetic'], meaning: '静女其姝，寓意美丽端庄。', source: '《诗经·邶风》' }),
  C({ char: '妍', wuxing: '水', pinyin: 'yán', simplifiedStrokes: 7, traditionalStrokes: 9, radical: '女', structure: '左右', gender: 'female', styles: ['classical', 'modern'], meaning: '百花争妍，寓意美好秀丽。', source: '《说文解字》' }),
  C({ char: '妮', wuxing: '火', pinyin: 'nī', simplifiedStrokes: 8, traditionalStrokes: 8, radical: '女', structure: '左右', gender: 'female', styles: ['modern', 'warm'], meaning: '亲昵可爱，寓意娇俏灵动。', source: '现代常用名用字' }),
  C({ char: '娇', wuxing: '木', pinyin: 'jiāo', simplifiedStrokes: 9, traditionalStrokes: 15, radical: '女', structure: '左右', gender: 'female', styles: ['classical', 'warm'], meaning: '千娇百媚，寓意娇美动人。', source: '《说文解字》' }),
  C({ char: '佳', wuxing: '木', pinyin: 'jiā', simplifiedStrokes: 8, traditionalStrokes: 8, radical: '亻', structure: '左右', gender: 'female', styles: ['warm', 'classical'], meaning: '佳人良辰，寓意美好出众。', source: '《说文解字》' }),
  C({ char: '俊', wuxing: '火', pinyin: 'jùn', simplifiedStrokes: 9, traditionalStrokes: 9, radical: '亻', structure: '左右', gender: 'male', styles: ['grand', 'modern'], meaning: '俊杰英才，寓意才智超群。', source: '《说文解字》' }),
  C({ char: '伟', wuxing: '土', pinyin: 'wěi', simplifiedStrokes: 6, traditionalStrokes: 11, radical: '亻', structure: '左右', gender: 'male', styles: ['grand', 'modern'], meaning: '丰功伟绩，寓意成就卓越。', source: '《说文解字》' }),
  C({ char: '强', wuxing: '木', pinyin: 'qiáng', simplifiedStrokes: 12, traditionalStrokes: 12, radical: '弓', structure: '左右', gender: 'male', styles: ['grand', 'modern'], meaning: '自强不息，寓意坚韧有力。', source: '《周易》' }),
  C({ char: '勇', wuxing: '土', pinyin: 'yǒng', simplifiedStrokes: 9, traditionalStrokes: 9, radical: '力', structure: '上下', gender: 'male', styles: ['grand', 'classical'], meaning: '勇往直前，寓意胆识过人。', source: '《说文解字》' }),
  C({ char: '勤', wuxing: '木', pinyin: 'qín', simplifiedStrokes: 13, traditionalStrokes: 13, radical: '力', structure: '左右', gender: 'male', styles: ['warm', 'classical'], meaning: '天道酬勤，寓意勤勉踏实。', source: '《尚书》' }),
  C({ char: '博', wuxing: '水', pinyin: 'bó', simplifiedStrokes: 12, traditionalStrokes: 12, radical: '十', structure: '左右', gender: 'male', styles: ['grand', 'classical'], meaning: '博学多才，寓意学识广博。', source: '《说文解字》' }),
  C({ char: '卓', wuxing: '火', pinyin: 'zhuó', simplifiedStrokes: 8, traditionalStrokes: 8, radical: '十', structure: '上下', gender: 'male', styles: ['grand', 'modern'], meaning: '卓尔不群，寓意出类拔萃。', source: '《论语》' }),
  C({ char: '修', wuxing: '金', pinyin: 'xiū', simplifiedStrokes: 9, traditionalStrokes: 10, radical: '亻', structure: '左右', gender: 'male', styles: ['classical', 'warm'], meaning: '修身齐家，寓意德行为人。', source: '《礼记·大学》' }),
  C({ char: '建', wuxing: '木', pinyin: 'jiàn', simplifiedStrokes: 8, traditionalStrokes: 9, radical: '廴', structure: '包围', gender: 'male', styles: ['grand', 'modern'], meaning: '建功立业，寓意有所作为。', source: '《说文解字》' }),
  C({ char: '德', wuxing: '火', pinyin: 'dé', simplifiedStrokes: 15, traditionalStrokes: 15, radical: '彳', structure: '左右', gender: 'male', styles: ['classical', 'grand'], meaning: '厚德载物，寓意品德高尚。', source: '《周易》' }),
  C({ char: '志', wuxing: '火', pinyin: 'zhì', simplifiedStrokes: 7, traditionalStrokes: 7, radical: '心', structure: '上下', gender: 'male', styles: ['grand', 'classical'], meaning: '志存高远，寓意志向坚定。', source: '《说文解字》' }),
  C({ char: '思', wuxing: '金', pinyin: 'sī', simplifiedStrokes: 9, traditionalStrokes: 9, radical: '心', structure: '上下', gender: 'neutral', styles: ['poetic', 'classical'], meaning: '见贤思齐，寓意善思明辨。', source: '《论语》' }),
  C({ char: '念2', wuxing: '火', pinyin: 'niàn', simplifiedStrokes: 8, traditionalStrokes: 8, radical: '心', structure: '上下', gender: 'neutral', styles: ['poetic'], meaning: 'placeholder', source: '' }),
  C({ char: '惠', wuxing: '水', pinyin: 'huì', simplifiedStrokes: 12, traditionalStrokes: 12, radical: '心', structure: '上下', gender: 'female', styles: ['warm', 'classical'], meaning: '惠风和畅，寓意仁惠温柔。', source: '王羲之《兰亭集序》' }),
  C({ char: '恩', wuxing: '土', pinyin: 'ēn', simplifiedStrokes: 10, traditionalStrokes: 10, radical: '心', structure: '上下', gender: 'neutral', styles: ['warm', 'classical'], meaning: '知恩图报，寓意感恩仁厚。', source: '《说文解字》' }),
  C({ char: '心', wuxing: '金', pinyin: 'xīn', simplifiedStrokes: 4, traditionalStrokes: 4, radical: '心', structure: '独体', gender: 'female', styles: ['warm', 'poetic'], meaning: '赤子之心，寓意真诚纯粹。', source: '《孟子》' }),
  C({ char: '敏', wuxing: '水', pinyin: 'mǐn', simplifiedStrokes: 11, traditionalStrokes: 11, radical: '攵', structure: '左右', gender: 'neutral', styles: ['classical', 'modern'], meaning: '敏而好学，寓意聪慧勤勉。', source: '《论语》' }),
  C({ char: '然', wuxing: '金', pinyin: 'rán', simplifiedStrokes: 12, traditionalStrokes: 12, radical: '灬', structure: '上下', gender: 'neutral', styles: ['poetic', 'classical'], meaning: '浩然自若，寓意从容坦荡。', source: '《说文解字》' }),
  C({ char: '煦', wuxing: '金', pinyin: 'xù', simplifiedStrokes: 13, traditionalStrokes: 13, radical: '灬', structure: '上下', gender: 'neutral', styles: ['warm', 'poetic'], meaning: '煦煦春风，寓意温暖和煦。', source: '《说文解字》' }),
  C({ char: '熙', wuxing: '水', pinyin: 'xī', simplifiedStrokes: 14, traditionalStrokes: 13, radical: '灬', structure: '上下', gender: 'neutral', styles: ['warm', 'classical'], meaning: '熙熙攘攘，寓意和乐兴盛。', source: '《说文解字》' }),
  C({ char: '旭2', wuxing: '火', pinyin: 'xù', simplifiedStrokes: 6, traditionalStrokes: 6, radical: '日', structure: '包围', gender: 'male', styles: ['grand'], meaning: 'placeholder', source: '' }),
  C({ char: '琦', wuxing: '木', pinyin: 'qí', simplifiedStrokes: 12, traditionalStrokes: 13, radical: '王', structure: '左右', gender: 'neutral', styles: ['classical', 'poetic'], meaning: '琦行瑰意，寓意不凡卓异。', source: '《说文解字》' }),
  C({ char: '琰', wuxing: '火', pinyin: 'yǎn', simplifiedStrokes: 12, traditionalStrokes: 13, radical: '王', structure: '左右', gender: 'male', styles: ['classical', 'poetic'], meaning: '琰琰生辉，寓意美好光亮。', source: '《说文解字》' }),
  C({ char: '琼', wuxing: '木', pinyin: 'qióng', simplifiedStrokes: 12, traditionalStrokes: 20, radical: '王', structure: '左右', gender: 'female', styles: ['classical', 'poetic'], meaning: '琼楼玉宇，寓意华美珍贵。', source: '《说文解字》' }),
  C({ char: '琨', wuxing: '木', pinyin: 'kūn', simplifiedStrokes: 12, traditionalStrokes: 13, radical: '王', structure: '左右', gender: 'male', styles: ['classical', 'grand'], meaning: '琨玉秋霜，寓意高洁贵重。', source: '《说文解字》' }),
  C({ char: '珩', wuxing: '水', pinyin: 'héng', simplifiedStrokes: 10, traditionalStrokes: 11, radical: '王', structure: '左右', gender: 'male', styles: ['classical', 'poetic'], meaning: '珩为佩玉，寓意君子之德。', source: '《说文解字》' }),
  C({ char: '瑄', wuxing: '金', pinyin: 'xuān', simplifiedStrokes: 13, traditionalStrokes: 14, radical: '王', structure: '左右', gender: 'female', styles: ['classical', 'poetic'], meaning: '瑄玉祭天，寓意庄重尊贵。', source: '《说文解字》' }),
  C({ char: '璨', wuxing: '金', pinyin: 'càn', simplifiedStrokes: 17, traditionalStrokes: 18, radical: '王', structure: '左右', gender: 'male', styles: ['poetic', 'grand'], meaning: '璀璨夺目，寓意光彩照人。', source: '《说文解字》' }),
  C({ char: '璞', wuxing: '水', pinyin: 'pú', simplifiedStrokes: 16, traditionalStrokes: 17, radical: '王', structure: '左右', gender: 'male', styles: ['classical', 'poetic'], meaning: '返璞归真，寓意天然本真。', source: '《老子》' }),
  C({ char: '璟', wuxing: '火', pinyin: 'jǐng', simplifiedStrokes: 16, traditionalStrokes: 17, radical: '王', structure: '左右', gender: 'male', styles: ['classical', 'grand'], meaning: '玉光为璟，寓意光彩耀眼。', source: '《说文解字》' }),
  C({ char: '溪2', wuxing: '水', pinyin: 'xī', simplifiedStrokes: 13, traditionalStrokes: 14, radical: '氵', structure: '左右', gender: 'female', styles: ['poetic'], meaning: 'placeholder', source: '' }),
  C({ char: '烁2', wuxing: '火', pinyin: 'shuò', simplifiedStrokes: 9, traditionalStrokes: 9, radical: '火', structure: '左右', gender: 'male', styles: ['grand'], meaning: 'placeholder', source: '' }),
]

// 去除占位符与重复字符，得到正式字库
export const NAMING_CHAR_POOL: NamingChar[] = (() => {
  const seen = new Set<string>()
  const out: NamingChar[] = []
  for (const c of CHAR_POOL) {
    if (c.meaning === 'placeholder') continue
    if (seen.has(c.char)) continue
    seen.add(c.char)
    out.push(c)
  }
  return out
})()
