import { defineConfig } from 'drizzle-kit'

// Drizzle config for the self-hosted better-auth + user_profiles SQLite store.
// Schema is generated by `npx better-auth generate` (core auth tables) plus the
// app-owned user_profiles table appended in the same file.
export default defineConfig({
  dialect: 'sqlite',
  schema: './server/utils/schema.ts',
  out: './server/db/migrations',
  dbCredentials: {
    url: process.env.AUTH_DB_PATH || './auth.db',
  },
})
