// Fixed glossary for article translation — keeps metaphysics terms consistent
// across articles. English renderings follow i18n/locales/en.json usage.
// Append-only: add new terms, never change an existing rendering.
export const TRANSLATION_GLOSSARY: ReadonlyArray<readonly [string, string]> = [
  ['命见', 'MingJian Insights'],
  ['幽默隐士', 'Hermit Humor'],
  ['八字', 'BaZi (Four Pillars of Destiny)'],
  ['子平八字', 'Zi Ping BaZi'],
  ['紫微斗数', 'Zi Wei Dou Shu'],
  ['六爻', 'Liu Yao'],
  ['梅花易数', 'Plum Blossom Numerology (Meihua Yishu)'],
  ['奇门遁甲', 'Qi Men Dun Jia'],
  ['大六壬', 'Da Liu Ren'],
  ['小六壬', 'Xiao Liu Ren'],
  ['太乙神数', 'Tai Yi Shen Shu'],
  ['风水', 'Feng Shui'],
  ['玄空飞星', 'Xuan Kong Flying Star'],
  ['紫白飞星', 'Zi Bai Fei Xing'],
  ['八宅', 'Ba Zhai'],
  ['财位', 'Wealth Position'],
  ['明财位', 'Ming Cai Wei (Visible Wealth Position)'],
  ['五行', 'Five Elements (Wu Xing)'],
  ['天干', 'Heavenly Stems'],
  ['地支', 'Earthly Branches'],
  ['十神', 'Ten Gods'],
  ['日主', 'Day Master'],
  ['大运', 'Luck Pillars'],
  ['流年', 'Annual Fortune'],
  ['太岁', 'Tai Sui'],
  ['犯太岁', 'Fan Tai Sui (clashing with Tai Sui)'],
  ['生肖', 'Chinese Zodiac'],
  ['冲太岁', 'Chong Tai Sui (opposing Tai Sui)'],
  ['黄道吉日', 'Auspicious Dates'],
  ['易经', 'I Ching'],
  ['周易', 'Zhou Yi'],
  ['测字', 'Ce Zi (Chinese Character Divination)'],
  ['灵签', 'Fortune Sticks'],
  ['观音灵签', 'Guanyin Fortune Sticks'],
  ['摇卦', 'Coin Casting'],
  ['紫微', 'Zi Wei'],
  ['合盘', 'Synastry'],
  ['命盘', 'Destiny Chart'],
  ['星盘', 'Birth Chart'],
  ['吠陀占星', 'Vedic Astrology'],
  ['塔罗', 'Tarot'],
  ['聚宝盆', 'Ju Bao Pen (Treasure Bowl)'],
  ['貔貅', 'Pi Xiu'],
  ['富贵竹', 'Lucky Bamboo'],
  ['紫晶洞', 'Amethyst Geode'],
  ['文昌位', 'Wenchang Position (Scholastic Corner)'],
  ['桃花位', 'Peach Blossom Position'],
  ['罗盘', 'Luo Pan (Feng Shui Compass)'],
  ['财神', 'Cai Shen (God of Wealth)'],
  ['开运', 'Luck Enhancement'],
]

export function glossaryPromptBlock(): string {
  return TRANSLATION_GLOSSARY.map(([zh, en]) => `   ${zh} → ${en}`).join('\n')
}
