import type {
  CeziZhouyiCharacterAnalysis,
  CeziZhouyiHexagram,
  CeziZhouyiRequest,
  CeziZhouyiResult,
} from '~/types/cezi-zhouyi'

const TRIGRAMS = [
  { symbol: '☷', name: '坤', nature: '地', wuxing: '土' },
  { symbol: '☶', name: '艮', nature: '山', wuxing: '土' },
  { symbol: '☵', name: '坎', nature: '水', wuxing: '水' },
  { symbol: '☴', name: '巽', nature: '风', wuxing: '木' },
  { symbol: '☳', name: '震', nature: '雷', wuxing: '木' },
  { symbol: '☲', name: '离', nature: '火', wuxing: '火' },
  { symbol: '☱', name: '兑', nature: '泽', wuxing: '金' },
  { symbol: '☰', name: '乾', nature: '天', wuxing: '金' },
]

const HEXAGRAM_NAMES: Record<string, string> = {
  '乾乾': '乾', '乾坤': '否', '乾艮': '遁', '乾兑': '履', '乾离': '同人', '乾坎': '讼', '乾震': '无妄', '乾巽': '姤',
  '坤乾': '泰', '坤坤': '坤', '坤艮': '谦', '坤兑': '临', '坤离': '明夷', '坤坎': '师', '坤震': '复', '坤巽': '升',
  '艮乾': '大畜', '艮坤': '剥', '艮艮': '艮', '艮兑': '损', '艮离': '贲', '艮坎': '蒙', '艮震': '颐', '艮巽': '蛊',
  '兑乾': '夬', '兑坤': '萃', '兑艮': '咸', '兑兑': '兑', '兑离': '革', '兑坎': '困', '兑震': '随', '兑巽': '大过',
  '离乾': '大有', '离坤': '晋', '离艮': '旅', '离兑': '睽', '离离': '离', '离坎': '未济', '离震': '噬嗑', '离巽': '鼎',
  '坎乾': '需', '坎坤': '比', '坎艮': '蹇', '坎兑': '节', '坎离': '既济', '坎坎': '坎', '坎震': '屯', '坎巽': '井',
  '震乾': '大壮', '震坤': '豫', '震艮': '小过', '震兑': '归妹', '震离': '丰', '震坎': '解', '震震': '震', '震巽': '恒',
  '巽乾': '小畜', '巽坤': '观', '巽艮': '渐', '巽兑': '中孚', '巽离': '家人', '巽坎': '涣', '巽震': '益', '巽巽': '巽',
}

export const CHAR_DATA: Record<string, {
  pinyin: string
  strokes: number
  radical: string
  components: string[]
  wuxing: string
  structure: string
  meaning: string
}> = {
  一: { pinyin: 'yī', strokes: 1, radical: '一', components: ['一'], wuxing: '土', structure: '独体字', meaning: '数之始，万物之本，象征开创与统一。' },
  乙: { pinyin: 'yǐ', strokes: 1, radical: '乙', components: ['乙'], wuxing: '木', structure: '独体字', meaning: '天干第二位，象征曲折生长、柔韧应变。' },
  二: { pinyin: 'èr', strokes: 2, radical: '二', components: ['二'], wuxing: '火', structure: '独体字', meaning: '偶数、对立与配合，象征平衡与选择。' },
  十: { pinyin: 'shí', strokes: 2, radical: '十', components: ['十'], wuxing: '金', structure: '独体字', meaning: '完备之数，象征圆满、终结与新的开始。' },
  人: { pinyin: 'rén', strokes: 2, radical: '人', components: ['人'], wuxing: '金', structure: '独体字', meaning: '天地之间最贵者，象征关系、仁德与自我。' },
  入: { pinyin: 'rù', strokes: 2, radical: '入', components: ['入'], wuxing: '火', structure: '独体字', meaning: '由外而内，象征进入、接纳与转变。' },
  八: { pinyin: 'bā', strokes: 2, radical: '八', components: ['八'], wuxing: '木', structure: '独体字', meaning: '分别之象，象征分散、变化与多元。' },
  几: { pinyin: 'jǐ', strokes: 2, radical: '几', components: ['几'], wuxing: '木', structure: '独体字', meaning: '微小之器，象征机微、征兆与未定之势。' },
  九: { pinyin: 'jiǔ', strokes: 2, radical: '乙', components: ['九'], wuxing: '木', structure: '独体字', meaning: '阳数之极，象征极致、圆满与转折。' },
  了: { pinyin: 'le', strokes: 2, radical: '亅', components: ['了'], wuxing: '火', structure: '独体字', meaning: '了结、完成，象征事情的终结与放下。' },
  力: { pinyin: 'lì', strokes: 2, radical: '力', components: ['力'], wuxing: '火', structure: '独体字', meaning: '筋力之象，象征力量、行动与进取。' },
  刀: { pinyin: 'dāo', strokes: 2, radical: '刀', components: ['刀'], wuxing: '金', structure: '独体字', meaning: '锐利之器，象征决断、分离与风险。' },
  又: { pinyin: 'yòu', strokes: 2, radical: '又', components: ['又'], wuxing: '土', structure: '独体字', meaning: '手之象，象征重复、再次与辅助。' },
  三: { pinyin: 'sān', strokes: 3, radical: '一', components: ['三'], wuxing: '金', structure: '独体字', meaning: '天地人三才，象征完整、稳定与生发。' },
  上: { pinyin: 'shàng', strokes: 3, radical: '一', components: ['上'], wuxing: '金', structure: '独体字', meaning: '高处、升进，象征向上、进取与目标。' },
  下: { pinyin: 'xià', strokes: 3, radical: '一', components: ['下'], wuxing: '水', structure: '独体字', meaning: '低处、沉降，象征根基、潜伏与等待。' },
  千: { pinyin: 'qiān', strokes: 3, radical: '十', components: ['千'], wuxing: '金', structure: '独体字', meaning: '大数之始，象征广阔、众多与长久。' },
  大: { pinyin: 'dà', strokes: 3, radical: '大', components: ['大'], wuxing: '火', structure: '独体字', meaning: '人展两臂，象征宏大、包容与担当。' },
  女: { pinyin: 'nǚ', strokes: 3, radical: '女', components: ['女'], wuxing: '火', structure: '独体字', meaning: '女子跪坐之象，象征柔顺、包容与情感。' },
  子: { pinyin: 'zǐ', strokes: 3, radical: '子', components: ['子'], wuxing: '水', structure: '独体字', meaning: '幼子之象，象征新生、起始与智慧。' },
  山: { pinyin: 'shān', strokes: 3, radical: '山', components: ['山'], wuxing: '土', structure: '独体字', meaning: '三峰并立，象征稳固、阻碍与崇高。' },
  川: { pinyin: 'chuān', strokes: 3, radical: '川', components: ['川'], wuxing: '金', structure: '独体字', meaning: '水流之象，象征流动、通达与变化。' },
  工: { pinyin: 'gōng', strokes: 3, radical: '工', components: ['工'], wuxing: '木', structure: '独体字', meaning: '工匠之器，象征技艺、劳作与规矩。' },
  土: { pinyin: 'tǔ', strokes: 3, radical: '土', components: ['土'], wuxing: '土', structure: '独体字', meaning: '大地之象，象征承载、稳固与养育。' },
  士: { pinyin: 'shì', strokes: 3, radical: '士', components: ['士'], wuxing: '金', structure: '独体字', meaning: '武士之象，象征志向、操守与进取。' },
  才: { pinyin: 'cái', strokes: 3, radical: '扌', components: ['才'], wuxing: '金', structure: '独体字', meaning: '草木初生，象征才华、能力与生机。' },
  寸: { pinyin: 'cùn', strokes: 3, radical: '寸', components: ['寸'], wuxing: '金', structure: '独体字', meaning: '寸口之象，象征分寸、尺度与节制。' },
  小: { pinyin: 'xiǎo', strokes: 3, radical: '小', components: ['小'], wuxing: '金', structure: '独体字', meaning: '细微之象，象征谨慎、内敛与精微。' },
  干: { pinyin: 'gàn', strokes: 3, radical: '干', components: ['干'], wuxing: '木', structure: '独体字', meaning: '盾之象，象征主干、防御与界限。' },
  万: { pinyin: 'wàn', strokes: 3, radical: '一', components: ['万'], wuxing: '水', structure: '独体字', meaning: '众数之极，象征丰富、繁盛与久远。' },
  飞: { pinyin: 'fēi', strokes: 3, radical: '飞', components: ['飞'], wuxing: '水', structure: '独体字', meaning: '鸟飞之象，象征升腾、自由与变化。' },
  马: { pinyin: 'mǎ', strokes: 3, radical: '马', components: ['马'], wuxing: '水', structure: '独体字', meaning: '骏马之象，象征迅速、奔腾与远行。' },
  王: { pinyin: 'wáng', strokes: 4, radical: '王', components: ['王'], wuxing: '土', structure: '独体字', meaning: '玉之象，象征尊贵、权威与中心。' },
  天: { pinyin: 'tiān', strokes: 4, radical: '大', components: ['一', '大'], wuxing: '火', structure: '上下结构', meaning: '至高无上，象征天道、规律与广阔。' },
  太: { pinyin: 'tài', strokes: 4, radical: '大', components: ['大', '丶'], wuxing: '火', structure: '独体字', meaning: '极大之象，象征顶点、极致与长辈。' },
  夫: { pinyin: 'fū', strokes: 4, radical: '大', components: ['夫'], wuxing: '水', structure: '独体字', meaning: '成人男子，象征责任、担当与主导。' },
  木: { pinyin: 'mù', strokes: 4, radical: '木', components: ['木'], wuxing: '木', structure: '独体字', meaning: '树木之象，象征生长、仁德与生机。' },
  水: { pinyin: 'shuǐ', strokes: 4, radical: '水', components: ['水'], wuxing: '水', structure: '独体字', meaning: '水流曲折，象征智慧、流动与险阻。' },
  火: { pinyin: 'huǒ', strokes: 4, radical: '火', components: ['火'], wuxing: '火', structure: '独体字', meaning: '火焰升腾，象征光明、热情与消耗。' },
  心: { pinyin: 'xīn', strokes: 4, radical: '心', components: ['心'], wuxing: '金', structure: '独体字', meaning: '心脏之象，象征思想、情感与核心。' },
  日: { pinyin: 'rì', strokes: 4, radical: '日', components: ['日'], wuxing: '火', structure: '独体字', meaning: '太阳之象，象征光明、时间与时运。' },
  月: { pinyin: 'yuè', strokes: 4, radical: '月', components: ['月'], wuxing: '木', structure: '独体字', meaning: '月亮之象，象征阴柔、周期与情感。' },
  文: { pinyin: 'wén', strokes: 4, radical: '文', components: ['文'], wuxing: '水', structure: '独体字', meaning: '纹之象，象征文化、文明与修饰。' },
  方: { pinyin: 'fāng', strokes: 4, radical: '方', components: ['方'], wuxing: '水', structure: '独体字', meaning: '并船之象，象征方向、规则与方正。' },
  无: { pinyin: 'wú', strokes: 4, radical: '一', components: ['无'], wuxing: '水', structure: '独体字', meaning: '虚无之象，象征空无、自在与超越。' },
  不: { pinyin: 'bù', strokes: 4, radical: '一', components: ['不'], wuxing: '水', structure: '独体字', meaning: '否定之象，象征阻碍、拒绝与边界。' },
  中: { pinyin: 'zhōng', strokes: 4, radical: '丨', components: ['口', '丨'], wuxing: '火', structure: '独体字', meaning: '中央之象，象征中正、平衡与核心。' },
  五: { pinyin: 'wǔ', strokes: 4, radical: '二', components: ['五'], wuxing: '木', structure: '独体字', meaning: '五行之数，象征平衡、中心与完整。' },
  六: { pinyin: 'liù', strokes: 4, radical: '八', components: ['六'], wuxing: '火', structure: '独体字', meaning: '六合之数，象征和谐、圆满与包容。' },
  七: { pinyin: 'qī', strokes: 2, radical: '一', components: ['七'], wuxing: '火', structure: '独体字', meaning: '少阳之数，象征变化、转折与生机。' },
  分: { pinyin: 'fēn', strokes: 4, radical: '刀', components: ['八', '刀'], wuxing: '水', structure: '上下结构', meaning: '分割之象，象征分别、分配与决断。' },
  公: { pinyin: 'gōng', strokes: 4, radical: '八', components: ['八', '厶'], wuxing: '木', structure: '上下结构', meaning: '公平之象，象征公共、正直与共享。' },
  今: { pinyin: 'jīn', strokes: 4, radical: '人', components: ['人', '丶', '㇇'], wuxing: '木', structure: '上下结构', meaning: '当下之象，象征现在、时机与把握。' },
  以: { pinyin: 'yǐ', strokes: 4, radical: '人', components: ['㕣', '丶'], wuxing: '土', structure: '左右结构', meaning: '用之象，象征凭借、依据与方法。' },
  化: { pinyin: 'huà', strokes: 4, radical: '亻', components: ['亻', '匕'], wuxing: '水', structure: '左右结构', meaning: '变化之象，象征转化、教化与消融。' },
  比: { pinyin: 'bǐ', strokes: 4, radical: '比', components: ['比'], wuxing: '水', structure: '左右结构', meaning: '并列之象，象征比较、亲比与竞争。' },
  友: { pinyin: 'yǒu', strokes: 4, radical: '又', components: ['又', '又'], wuxing: '土', structure: '半包围结构', meaning: '携手之象，象征友谊、互助与亲近。' },
  双: { pinyin: 'shuāng', strokes: 4, radical: '又', components: ['又', '又'], wuxing: '金', structure: '左右结构', meaning: '成对之象，象征成双、配合与圆满。' },
  反: { pinyin: 'fǎn', strokes: 4, radical: '又', components: ['反'], wuxing: '水', structure: '半包围结构', meaning: '反转之象，象征反复、回归与反思。' },
  世: { pinyin: 'shì', strokes: 5, radical: '一', components: ['廿', '乚'], wuxing: '金', structure: '独体字', meaning: '世代之象，象征世界、时代与传承。' },
  本: { pinyin: 'běn', strokes: 5, radical: '木', components: ['木', '一'], wuxing: '木', structure: '独体字', meaning: '根本之象，象征本源、基础与主体。' },
  末: { pinyin: 'mò', strokes: 5, radical: '木', components: ['木', '一'], wuxing: '水', structure: '独体字', meaning: '末梢之象，象征末端、细微与衰落。' },
  未: { pinyin: 'wèi', strokes: 5, radical: '木', components: ['未'], wuxing: '木', structure: '独体字', meaning: '地支第八位，象征未来、未知与希望。' },
  正: { pinyin: 'zhèng', strokes: 5, radical: '止', components: ['一', '止'], wuxing: '金', structure: '独体字', meaning: '正直之象，象征公正、正确与稳定。' },
  玉: { pinyin: 'yù', strokes: 5, radical: '玉', components: ['玉'], wuxing: '木', structure: '独体字', meaning: '美石之象，象征珍贵、纯洁与德行。' },
  生: { pinyin: 'shēng', strokes: 5, radical: '生', components: ['生'], wuxing: '金', structure: '独体字', meaning: '草木生长，象征生命、发生与产出。' },
  用: { pinyin: 'yòng', strokes: 5, radical: '用', components: ['用'], wuxing: '土', structure: '独体字', meaning: '可施行之象，象征功用、实用与运用。' },
  田: { pinyin: 'tián', strokes: 5, radical: '田', components: ['田'], wuxing: '火', structure: '独体字', meaning: '田地之象，象征根基、财富与安定。' },
  白: { pinyin: 'bái', strokes: 5, radical: '白', components: ['白'], wuxing: '水', structure: '独体字', meaning: '明亮之象，象征清白、明白与空虚。' },
  石: { pinyin: 'shí', strokes: 5, radical: '石', components: ['石'], wuxing: '金', structure: '独体字', meaning: '山石之象，象征坚固、阻碍与持久。' },
  立: { pinyin: 'lì', strokes: 5, radical: '立', components: ['立'], wuxing: '火', structure: '独体字', meaning: '站立之象，象征建立、独立与开始。' },
  龙: { pinyin: 'lóng', strokes: 5, radical: '龙', components: ['龙'], wuxing: '火', structure: '独体字', meaning: '神兽之象，象征尊贵、变化与祥瑞。' },
  目: { pinyin: 'mù', strokes: 5, radical: '目', components: ['目'], wuxing: '水', structure: '独体字', meaning: '眼睛之象，象征观察、目标与明辨。' },
  四: { pinyin: 'sì', strokes: 5, radical: '囗', components: ['囗', '儿'], wuxing: '金', structure: '全包围结构', meaning: '四方之象，象征稳定、周全与界限。' },
  民: { pinyin: 'mín', strokes: 5, radical: '乛', components: ['民'], wuxing: '水', structure: '独体字', meaning: '民众之象，象征基础、依附与众生。' },
  出: { pinyin: 'chū', strokes: 5, radical: '凵', components: ['山', '山'], wuxing: '金', structure: '上下结构', meaning: '出入之象，象征外出、显现与产生。' },
  半: { pinyin: 'bàn', strokes: 5, radical: '十', components: ['丶', '丷', '干'], wuxing: '水', structure: '独体字', meaning: '中间之象，象征 incomplete、过渡与平衡。' },
  打: { pinyin: 'dǎ', strokes: 5, radical: '扌', components: ['扌', '丁'], wuxing: '火', structure: '左右结构', meaning: '击打之象，象征行动、开始与接触。' },
  北: { pinyin: 'běi', strokes: 5, radical: '匕', components: ['匕', '匕'], wuxing: '水', structure: '左右结构', meaning: '北方之象，象征背离、方向与寒冬。' },
  占: { pinyin: 'zhān', strokes: 5, radical: '卜', components: ['卜', '口'], wuxing: '金', structure: '上下结构', meaning: '占卜之象，象征预测、占据与判断。' },
  卡: { pinyin: 'kǎ', strokes: 5, radical: '丨', components: ['上', '下'], wuxing: '木', structure: '上下结构', meaning: '卡住之象，象征关卡、停顿与选择。' },
  古: { pinyin: 'gǔ', strokes: 5, radical: '口', components: ['十', '口'], wuxing: '木', structure: '上下结构', meaning: '古老之象，象征传统、经验与恒久。' },
  可: { pinyin: 'kě', strokes: 5, radical: '口', components: ['丁', '口'], wuxing: '木', structure: '半包围结构', meaning: '许可之象，象征可能、认可与可行。' },
  吉: { pinyin: 'jí', strokes: 6, radical: '口', components: ['士', '口'], wuxing: '木', structure: '上下结构', meaning: '吉祥之象，象征吉利、顺遂与美好。' },
  老: { pinyin: 'lǎo', strokes: 6, radical: '耂', components: ['耂', '匕'], wuxing: '火', structure: '半包围结构', meaning: '年老之象，象征成熟、经验与衰退。' },
  至: { pinyin: 'zhì', strokes: 6, radical: '至', components: ['至'], wuxing: '火', structure: '独体字', meaning: '到达之象，象征极致、归宿与完成。' },
  成: { pinyin: 'chéng', strokes: 6, radical: '戈', components: ['戊', '𠃌', '丶'], wuxing: '金', structure: '独体字', meaning: '完成之象，象征成就、成功与结果。' },
  同: { pinyin: 'tóng', strokes: 6, radical: '口', components: ['冂', '一', '口'], wuxing: '火', structure: '半包围结构', meaning: '共同之象，象征协同、一致与聚合。' },
  因: { pinyin: 'yīn', strokes: 6, radical: '囗', components: ['囗', '大'], wuxing: '土', structure: '全包围结构', meaning: '因缘之象，象征原因、依托与包容。' },
  回: { pinyin: 'huí', strokes: 6, radical: '囗', components: ['囗', '口'], wuxing: '水', structure: '全包围结构', meaning: '回转之象，象征回归、反复与循环。' },
  行: { pinyin: 'xíng', strokes: 6, radical: '行', components: ['行'], wuxing: '水', structure: '左右结构', meaning: '道路之象，象征行动、行走与可行。' },
  名: { pinyin: 'míng', strokes: 6, radical: '口', components: ['夕', '口'], wuxing: '水', structure: '上下结构', meaning: '名称之象，象征名声、标识与召唤。' },
  多: { pinyin: 'duō', strokes: 6, radical: '夕', components: ['夕', '夕'], wuxing: '火', structure: '上下结构', meaning: '众多之象，象征丰富、过剩与分散。' },
  好: { pinyin: 'hǎo', strokes: 6, radical: '女', components: ['女', '子'], wuxing: '水', structure: '左右结构', meaning: '美好之象，象征和谐、友善与良缘。' },
  如: { pinyin: 'rú', strokes: 6, radical: '女', components: ['女', '口'], wuxing: '金', structure: '左右结构', meaning: '相似之象，象征顺从、如同与适宜。' },
  妇: { pinyin: 'fù', strokes: 6, radical: '女', components: ['女', '彐'], wuxing: '水', structure: '左右结构', meaning: '女子之象，象征家庭、柔顺与持守。' },
  安: { pinyin: 'ān', strokes: 6, radical: '宀', components: ['宀', '女'], wuxing: '土', structure: '上下结构', meaning: '安定之象，象征平安、安居与宁静。' },
  守: { pinyin: 'shǒu', strokes: 6, radical: '宀', components: ['宀', '寸'], wuxing: '金', structure: '上下结构', meaning: '守护之象，象征保守、持守与等待。' },
  家: { pinyin: 'jiā', strokes: 10, radical: '宀', components: ['宀', '豕'], wuxing: '木', structure: '上下结构', meaning: '居所之象，象征家庭、归宿与根基。' },
  官: { pinyin: 'guān', strokes: 8, radical: '宀', components: ['宀', '㠯'], wuxing: '木', structure: '上下结构', meaning: '官职之象，象征权力、地位与责任。' },
  富: { pinyin: 'fù', strokes: 12, radical: '宀', components: ['宀', '畐'], wuxing: '水', structure: '上下结构', meaning: '富有之象，象征财富、丰足与充盈。' },
  宝: { pinyin: 'bǎo', strokes: 8, radical: '宀', components: ['宀', '玉'], wuxing: '火', structure: '上下结构', meaning: '珍宝之象，象征珍贵、守护与价值。' },
  定: { pinyin: 'dìng', strokes: 8, radical: '宀', components: ['宀', '正'], wuxing: '火', structure: '上下结构', meaning: '确定之象，象征稳定、决定与安宁。' },
  宜: { pinyin: 'yí', strokes: 8, radical: '宀', components: ['宀', '且'], wuxing: '木', structure: '上下结构', meaning: '适宜之象，象征合适、应当与和顺。' },
  完: { pinyin: 'wán', strokes: 7, radical: '宀', components: ['宀', '元'], wuxing: '土', structure: '上下结构', meaning: '完整之象，象征圆满、终结与保全。' },
  进: { pinyin: 'jìn', strokes: 7, radical: '辶', components: ['辶', '井'], wuxing: '火', structure: '半包围结构', meaning: '前进之象，象征进展、进取与提升。' },
  退: { pinyin: 'tuì', strokes: 9, radical: '辶', components: ['辶', '艮'], wuxing: '火', structure: '半包围结构', meaning: '后退之象，象征退让、收敛与等待。' },
  远: { pinyin: 'yuǎn', strokes: 7, radical: '辶', components: ['辶', '元'], wuxing: '土', structure: '半包围结构', meaning: '遥远之象，象征距离、长远与开阔。' },
  近: { pinyin: 'jìn', strokes: 7, radical: '辶', components: ['辶', '斤'], wuxing: '木', structure: '半包围结构', meaning: '接近之象，象征临近、亲近与短期。' },
  还: { pinyin: 'huán', strokes: 7, radical: '辶', components: ['辶', '不'], wuxing: '水', structure: '半包围结构', meaning: '归还之象，象征返回、偿还与循环。' },
  运: { pinyin: 'yùn', strokes: 7, radical: '辶', components: ['辶', '云'], wuxing: '土', structure: '半包围结构', meaning: '运气之象，象征运势、运行与流转。' },
  道: { pinyin: 'dào', strokes: 12, radical: '辶', components: ['辶', '首'], wuxing: '火', structure: '半包围结构', meaning: '道路之象，象征道理、方向与规律。' },
  通: { pinyin: 'tōng', strokes: 10, radical: '辶', components: ['辶', '甬'], wuxing: '火', structure: '半包围结构', meaning: '通达之象，象征通畅、顺利与连接。' },
  连: { pinyin: 'lián', strokes: 7, radical: '辶', components: ['辶', '车'], wuxing: '火', structure: '半包围结构', meaning: '连接之象，象征连续、关联与拖延。' },
  迎: { pinyin: 'yíng', strokes: 7, radical: '辶', components: ['辶', '卬'], wuxing: '土', structure: '半包围结构', meaning: '迎接之象，象征欢迎、接纳与主动。' },
  送: { pinyin: 'sòng', strokes: 9, radical: '辶', components: ['辶', '关'], wuxing: '金', structure: '半包围结构', meaning: '送别之象，象征离别、馈赠与远行。' },
  过: { pinyin: 'guò', strokes: 6, radical: '辶', components: ['辶', '寸'], wuxing: '木', structure: '半包围结构', meaning: '经过之象，象征过渡、超越与经历。' },
  这: { pinyin: 'zhè', strokes: 7, radical: '辶', components: ['辶', '文'], wuxing: '火', structure: '半包围结构', meaning: '近指之象，象征当下、此处与确定。' },
  那: { pinyin: 'nà', strokes: 6, radical: '阝', components: ['那'], wuxing: '火', structure: '左右结构', meaning: '远指之象，象征远方、他人与距离。' },
  都: { pinyin: 'dōu', strokes: 10, radical: '阝', components: ['者', '阝'], wuxing: '火', structure: '左右结构', meaning: '总括之象，象征全部、都市与集中。' },
  部: { pinyin: 'bù', strokes: 10, radical: '阝', components: ['立', '口', '阝'], wuxing: '水', structure: '左右结构', meaning: '部分之象，象征部门、类别与分配。' },
  里: { pinyin: 'lǐ', strokes: 7, radical: '里', components: ['里'], wuxing: '火', structure: '独体字', meaning: '里巷之象，象征内部、距离与归属。' },
  外: { pinyin: 'wài', strokes: 5, radical: '夕', components: ['夕', '卜'], wuxing: '木', structure: '左右结构', meaning: '外部之象，象征外在、远方与排斥。' },
  内: { pinyin: 'nèi', strokes: 4, radical: '冂', components: ['冂', '人'], wuxing: '火', structure: '独体字', meaning: '内部之象，象征内在、包容与核心。' },
  东: { pinyin: 'dōng', strokes: 5, radical: '一', components: ['东'], wuxing: '木', structure: '独体字', meaning: '东方之象，象征生发、开始与朝气。' },
  西: { pinyin: 'xī', strokes: 6, radical: '覀', components: ['西'], wuxing: '金', structure: '独体字', meaning: '西方之象，象征收敛、成熟与归宿。' },
  南: { pinyin: 'nán', strokes: 9, radical: '十', components: ['南'], wuxing: '火', structure: '上下结构', meaning: '南方之象，象征光明、热情与繁盛。' },
  春: { pinyin: 'chūn', strokes: 9, radical: '日', components: ['三', '人', '日'], wuxing: '金', structure: '上下结构', meaning: '春天之象，象征生发、希望与开始。' },
  夏: { pinyin: 'xià', strokes: 10, radical: '夂', components: ['一', '自', '夂'], wuxing: '火', structure: '上下结构', meaning: '夏天之象，象征旺盛、热情与极致。' },
  秋: { pinyin: 'qiū', strokes: 9, radical: '禾', components: ['禾', '火'], wuxing: '金', structure: '左右结构', meaning: '秋天之象，象征收获、成熟与肃杀。' },
  冬: { pinyin: 'dōng', strokes: 5, radical: '夂', components: ['夂', '丶'], wuxing: '火', structure: '上下结构', meaning: '冬天之象，象征收藏、静止与蛰伏。' },
  风: { pinyin: 'fēng', strokes: 4, radical: '风', components: ['风'], wuxing: '水', structure: '半包围结构', meaning: '风气之象，象征变化、传播与影响。' },
  雨: { pinyin: 'yǔ', strokes: 8, radical: '雨', components: ['雨'], wuxing: '水', structure: '独体字', meaning: '雨水之象，象征滋润、恩泽与流动。' },
  雪: { pinyin: 'xuě', strokes: 11, radical: '雨', components: ['雨', '彐'], wuxing: '水', structure: '上下结构', meaning: '雪花之象，象征纯洁、寒冷与覆盖。' },
  云: { pinyin: 'yún', strokes: 4, radical: '二', components: ['云'], wuxing: '水', structure: '独体字', meaning: '云彩之象，象征变化、高远与虚无。' },
  电: { pinyin: 'diàn', strokes: 5, radical: '田', components: ['日', '乚'], wuxing: '火', structure: '独体字', meaning: '闪电之象，象征迅速、能量与突发。' },
  光: { pinyin: 'guāng', strokes: 6, radical: '儿', components: ['⺌', '兀'], wuxing: '火', structure: '上下结构', meaning: '光明之象，象征智慧、荣耀与显露。' },
  明: { pinyin: 'míng', strokes: 8, radical: '日', components: ['日', '月'], wuxing: '水', structure: '左右结构', meaning: '光明之象，象征明智、清晰与希望。' },
  时: { pinyin: 'shí', strokes: 7, radical: '日', components: ['日', '寸'], wuxing: '金', structure: '左右结构', meaning: '时间之象，象征时机、节律与变化。' },
  早: { pinyin: 'zǎo', strokes: 6, radical: '日', components: ['日', '十'], wuxing: '火', structure: '上下结构', meaning: '早晨之象，象征开始、提前与朝气。' },
  晚: { pinyin: 'wǎn', strokes: 11, radical: '日', components: ['日', '免'], wuxing: '水', structure: '左右结构', meaning: '夜晚之象，象征结束、迟暮与沉静。' },
  星: { pinyin: 'xīng', strokes: 9, radical: '日', components: ['日', '生'], wuxing: '金', structure: '上下结构', meaning: '星辰之象，象征指引、遥远与命运。' },
  有: { pinyin: 'yǒu', strokes: 6, radical: '月', components: ['𠂇', '月'], wuxing: '土', structure: '半包围结构', meaning: '拥有之象，象征存在、获得与充实。' },
  来: { pinyin: 'lái', strokes: 7, radical: '木', components: ['来'], wuxing: '火', structure: '独体字', meaning: '来临之象，象征到来、未来与趋向。' },
  去: { pinyin: 'qù', strokes: 5, radical: '厶', components: ['土', '厶'], wuxing: '木', structure: '上下结构', meaning: '离去之象，象征离开、消逝与方向。' },
  开: { pinyin: 'kāi', strokes: 4, radical: '廾', components: ['一', '廾'], wuxing: '木', structure: '独体字', meaning: '开启之象，象征开始、开放与通达。' },
  关: { pinyin: 'guān', strokes: 6, radical: '丷', components: ['丷', '天'], wuxing: '木', structure: '上下结构', meaning: '关闭之象，象征关卡、结束与关联。' },
  合: { pinyin: 'hé', strokes: 6, radical: '口', components: ['人', '一', '口'], wuxing: '水', structure: '上下结构', meaning: '和合之象，象征结合、配合与圆满。' },
  和: { pinyin: 'hé', strokes: 8, radical: '口', components: ['禾', '口'], wuxing: '水', structure: '左右结构', meaning: '和谐之象，象征平和、协调与融洽。' },
  平: { pinyin: 'píng', strokes: 5, radical: '干', components: ['一', '丷', '干'], wuxing: '水', structure: '独体字', meaning: '平坦之象，象征平稳、公平与安宁。' },
  喜: { pinyin: 'xǐ', strokes: 12, radical: '口', components: ['吉', '口'], wuxing: '水', structure: '上下结构', meaning: '喜悦之象，象征喜庆、欢乐与好事。' },
  乐: { pinyin: 'lè', strokes: 5, radical: '丿', components: ['乐'], wuxing: '火', structure: '独体字', meaning: '快乐之象，象征愉悦、轻松与满足。' },
  忧: { pinyin: 'yōu', strokes: 7, radical: '忄', components: ['忄', '尤'], wuxing: '土', structure: '左右结构', meaning: '忧虑之象，象征担忧、思虑与不安。' },
  愁: { pinyin: 'chóu', strokes: 13, radical: '心', components: ['秋', '心'], wuxing: '金', structure: '上下结构', meaning: '忧愁之象，象征烦恼、思虑与郁结。' },
  怒: { pinyin: 'nù', strokes: 9, radical: '心', components: ['奴', '心'], wuxing: '火', structure: '上下结构', meaning: '愤怒之象，象征冲动、力量与冲突。' },
  爱: { pinyin: 'ài', strokes: 10, radical: '爫', components: ['爫', '冖', '友'], wuxing: '土', structure: '上下结构', meaning: '喜爱之象，象征爱情、关怀与付出。' },
  情: { pinyin: 'qíng', strokes: 11, radical: '忄', components: ['忄', '青'], wuxing: '金', structure: '左右结构', meaning: '情感之象，象征感情、心情与关系。' },
  意: { pinyin: 'yì', strokes: 13, radical: '心', components: ['音', '心'], wuxing: '土', structure: '上下结构', meaning: '心意之象，象征意志、想法与意图。' },
  想: { pinyin: 'xiǎng', strokes: 13, radical: '心', components: ['相', '心'], wuxing: '金', structure: '上下结构', meaning: '思想之象，象征思考、想念与期望。' },
  念: { pinyin: 'niàn', strokes: 8, radical: '心', components: ['今', '心'], wuxing: '火', structure: '上下结构', meaning: '念虑之象，象征思念、念头与专注。' },
  忘: { pinyin: 'wàng', strokes: 7, radical: '心', components: ['亡', '心'], wuxing: '水', structure: '上下结构', meaning: '忘记之象，象征放下、消逝与解脱。' },
  感: { pinyin: 'gǎn', strokes: 13, radical: '心', components: ['咸', '心'], wuxing: '木', structure: '上下结构', meaning: '感触之象，象征感受、感动与体悟。' },
  快: { pinyin: 'kuài', strokes: 7, radical: '忄', components: ['忄', '夬'], wuxing: '木', structure: '左右结构', meaning: '迅速之象，象征快速、愉快与果断。' },
  慢: { pinyin: 'màn', strokes: 14, radical: '忄', components: ['忄', '曼'], wuxing: '水', structure: '左右结构', meaning: '缓慢之象，象征迟缓、沉稳与拖延。' },
  高: { pinyin: 'gāo', strokes: 10, radical: '高', components: ['高'], wuxing: '木', structure: '上下结构', meaning: '高处之象，象征崇高、目标与 distant。' },
  低: { pinyin: 'dī', strokes: 7, radical: '亻', components: ['亻', '氐'], wuxing: '火', structure: '左右结构', meaning: '低处之象，象征谦卑、下沉与基础。' },
  长: { pinyin: 'cháng', strokes: 4, radical: '长', components: ['长'], wuxing: '火', structure: '独体字', meaning: '长久之象，象征长远、成长与延续。' },
  短: { pinyin: 'duǎn', strokes: 12, radical: '矢', components: ['矢', '豆'], wuxing: '火', structure: '左右结构', meaning: '短促之象，象征短暂、局限与急促。' },
  少: { pinyin: 'shǎo', strokes: 4, radical: '小', components: ['小', '丿'], wuxing: '金', structure: '独体字', meaning: '稀少之象，象征不足、精简与年轻。' },
  男: { pinyin: 'nán', strokes: 7, radical: '田', components: ['田', '力'], wuxing: '火', structure: '上下结构', meaning: '男子之象，象征阳刚、力量与担当。' },
  父: { pinyin: 'fù', strokes: 4, radical: '父', components: ['父'], wuxing: '水', structure: '独体字', meaning: '父亲之象，象征权威、保护与传承。' },
  母: { pinyin: 'mǔ', strokes: 5, radical: '母', components: ['母'], wuxing: '水', structure: '独体字', meaning: '母亲之象，象征养育、包容与根源。' },
  兄: { pinyin: 'xiōng', strokes: 5, radical: '儿', components: ['口', '儿'], wuxing: '水', structure: '上下结构', meaning: '兄长之象，象征同辈、竞争与扶持。' },
  弟: { pinyin: 'dì', strokes: 7, radical: '弓', components: ['丷', '弓', '丿'], wuxing: '火', structure: '独体字', meaning: '弟弟之象，象征年幼、跟随与辅助。' },
  朋: { pinyin: 'péng', strokes: 8, radical: '月', components: ['月', '月'], wuxing: '水', structure: '左右结构', meaning: '朋友之象，象征同伴、合作与情谊。' },
  亲: { pinyin: 'qīn', strokes: 9, radical: '立', components: ['立', '木'], wuxing: '木', structure: '上下结构', meaning: '亲近之象，象征亲情、亲密与直接。' },
  师: { pinyin: 'shī', strokes: 6, radical: '巾', components: ['丨', '一', '巾'], wuxing: '金', structure: '左右结构', meaning: '师长之象，象征教导、权威与众人。' },
  财: { pinyin: 'cái', strokes: 7, radical: '贝', components: ['贝', '才'], wuxing: '金', structure: '左右结构', meaning: '财富之象，象征金钱、资源与价值。' },
  钱: { pinyin: 'qián', strokes: 10, radical: '钅', components: ['钅', '戋'], wuxing: '金', structure: '左右结构', meaning: '金钱之象，象征财富、交易与流通。' },
  金: { pinyin: 'jīn', strokes: 8, radical: '金', components: ['金'], wuxing: '金', structure: '上下结构', meaning: '金属之象，象征财富、坚固与收敛。' },
  银: { pinyin: 'yín', strokes: 11, radical: '钅', components: ['钅', '艮'], wuxing: '金', structure: '左右结构', meaning: '白银之象，象征财富、清白与稳定。' },
  贵: { pinyin: 'guì', strokes: 9, radical: '贝', components: ['中', '一', '贝'], wuxing: '木', structure: '上下结构', meaning: '尊贵之象，象征贵重、价值与地位。' },
  穷: { pinyin: 'qióng', strokes: 7, radical: '穴', components: ['穴', '力'], wuxing: '木', structure: '上下结构', meaning: '穷尽之象，象征困窘、极限与转机。' },
  利: { pinyin: 'lì', strokes: 7, radical: '刂', components: ['禾', '刂'], wuxing: '火', structure: '左右结构', meaning: '利益之象，象征收获、锋利与好处。' },
  权: { pinyin: 'quán', strokes: 6, radical: '木', components: ['木', '又'], wuxing: '木', structure: '左右结构', meaning: '权力之象，象征权威、掌控与影响。' },
  事: { pinyin: 'shì', strokes: 8, radical: '亅', components: ['一', '口', '亅'], wuxing: '金', structure: '独体字', meaning: '事务之象，象征事情、事业与责任。' },
  业: { pinyin: 'yè', strokes: 5, radical: '一', components: ['业'], wuxing: '木', structure: '独体字', meaning: '事业之象，象征行业、功业与基础。' },
  作: { pinyin: 'zuò', strokes: 7, radical: '亻', components: ['亻', '乍'], wuxing: '金', structure: '左右结构', meaning: '作为之象，象征行动、创作与职业。' },
  学: { pinyin: 'xué', strokes: 8, radical: '子', components: ['⺌', '冖', '子'], wuxing: '水', structure: '上下结构', meaning: '学习之象，象征学问、求知与成长。' },
  问: { pinyin: 'wèn', strokes: 6, radical: '门', components: ['门', '口'], wuxing: '金', structure: '半包围结构', meaning: '询问之象，象征求知、沟通与探索。' },
  答: { pinyin: 'dá', strokes: 12, radical: '竹', components: ['竹', '合'], wuxing: '木', structure: '上下结构', meaning: '回答之象，象征回应、解决与结果。' },
  看: { pinyin: 'kàn', strokes: 9, radical: '目', components: ['手', '目'], wuxing: '木', structure: '上下结构', meaning: '观察之象，象征审视、判断与预见。' },
  见: { pinyin: 'jiàn', strokes: 4, radical: '见', components: ['见'], wuxing: '木', structure: '独体字', meaning: '看见之象，象征遇见、发现与显现。' },
  听: { pinyin: 'tīng', strokes: 7, radical: '口', components: ['口', '斤'], wuxing: '火', structure: '左右结构', meaning: '听闻之象，象征倾听、消息与接受。' },
  说: { pinyin: 'shuō', strokes: 9, radical: '讠', components: ['讠', '兑'], wuxing: '金', structure: '左右结构', meaning: '言语之象，象征表达、沟通与说服。' },
  话: { pinyin: 'huà', strokes: 8, radical: '讠', components: ['讠', '舌'], wuxing: '土', structure: '左右结构', meaning: '话语之象，象征交流、信息与承诺。' },
  信: { pinyin: 'xìn', strokes: 9, radical: '亻', components: ['亻', '言'], wuxing: '金', structure: '左右结构', meaning: '诚信之象，象征信任、信念与可靠。' },
  真: { pinyin: 'zhēn', strokes: 10, radical: '目', components: ['十', '具'], wuxing: '金', structure: '上下结构', meaning: '真实之象，象征真诚、本质与确实。' },
  假: { pinyin: 'jiǎ', strokes: 11, radical: '亻', components: ['亻', '叚'], wuxing: '木', structure: '左右结构', meaning: '虚假之象，象征伪装、临时与试探。' },
  美: { pinyin: 'měi', strokes: 9, radical: '大', components: ['羊', '大'], wuxing: '水', structure: '上下结构', meaning: '美好之象，象征美丽、完善与吉祥。' },
  恶: { pinyin: 'è', strokes: 10, radical: '心', components: ['亚', '心'], wuxing: '土', structure: '上下结构', meaning: '恶劣之象，象征阻碍、凶险与厌恶。' },
  善: { pinyin: 'shàn', strokes: 12, radical: '口', components: ['羊', '言'], wuxing: '金', structure: '上下结构', meaning: '善良之象，象征吉祥、美好与德行。' },
  福: { pinyin: 'fú', strokes: 13, radical: '礻', components: ['礻', '畐'], wuxing: '水', structure: '左右结构', meaning: '福气之象，象征幸福、吉祥与庇佑。' },
  禄: { pinyin: 'lù', strokes: 12, radical: '礻', components: ['礻', '录'], wuxing: '火', structure: '左右结构', meaning: '俸禄之象，象征财富、地位与福报。' },
  寿: { pinyin: 'shòu', strokes: 7, radical: '寸', components: ['寿'], wuxing: '金', structure: '半包围结构', meaning: '长寿之象，象征健康、恒久与福泽。' },
  祥: { pinyin: 'xiáng', strokes: 10, radical: '礻', components: ['礻', '羊'], wuxing: '金', structure: '左右结构', meaning: '祥瑞之象，象征吉祥、和谐与好兆头。' },
  凶: { pinyin: 'xiōng', strokes: 4, radical: '凵', components: ['凶'], wuxing: '水', structure: '半包围结构', meaning: '凶险之象，象征危险、灾祸与不利。' },
  祸: { pinyin: 'huò', strokes: 11, radical: '礻', components: ['礻', '呙'], wuxing: '水', structure: '左右结构', meaning: '灾祸之象，象征祸患、损失与变故。' },
  难: { pinyin: 'nán', strokes: 10, radical: '隹', components: ['又', '隹'], wuxing: '木', structure: '左右结构', meaning: '困难之象，象征阻碍、考验与挑战。' },
  易: { pinyin: 'yì', strokes: 8, radical: '日', components: ['日', '勿'], wuxing: '火', structure: '上下结构', meaning: '变化之象，象征容易、变易与平易。' },
  变: { pinyin: 'biàn', strokes: 8, radical: '又', components: ['亦', '又'], wuxing: '水', structure: '上下结构', meaning: '变化之象，象征变动、转变与革新。' },
  新: { pinyin: 'xīn', strokes: 13, radical: '斤', components: ['立', '木', '斤'], wuxing: '金', structure: '左右结构', meaning: '新鲜之象，象征更新、开始与生机。' },
  旧: { pinyin: 'jiù', strokes: 5, radical: '日', components: ['丨', '日'], wuxing: '木', structure: '左右结构', meaning: '陈旧之象，象征过去、经验与固守。' },
  初: { pinyin: 'chū', strokes: 7, radical: '衤', components: ['衤', '刀'], wuxing: '金', structure: '左右结构', meaning: '初始之象，象征开始、初心与起源。' },
  终: { pinyin: 'zhōng', strokes: 8, radical: '纟', components: ['纟', '冬'], wuxing: '金', structure: '左右结构', meaning: '终结之象，象征结束、归宿与结果。' },
  始: { pinyin: 'shǐ', strokes: 8, radical: '女', components: ['女', '台'], wuxing: '金', structure: '左右结构', meaning: '开始之象，象征起源、开端与初心。' },
  永: { pinyin: 'yǒng', strokes: 5, radical: '水', components: ['永'], wuxing: '土', structure: '独体字', meaning: '永久之象，象征长久、恒远与延续。' },
  久: { pinyin: 'jiǔ', strokes: 3, radical: '丿', components: ['久'], wuxing: '木', structure: '独体字', meaning: '长久之象，象征持久、延误与等待。' },
  速: { pinyin: 'sù', strokes: 10, radical: '辶', components: ['辶', '束'], wuxing: '金', structure: '半包围结构', meaning: '迅速之象，象征快速、急切与短暂。' },
  迟: { pinyin: 'chí', strokes: 7, radical: '辶', components: ['辶', '尺'], wuxing: '金', structure: '半包围结构', meaning: '迟缓之象，象征拖延、稳重与等待。' },
  急: { pinyin: 'jí', strokes: 9, radical: '心', components: ['刍', '心'], wuxing: '木', structure: '上下结构', meaning: '急迫之象，象征紧急、焦虑与冲动。' },
  缓: { pinyin: 'huǎn', strokes: 12, radical: '纟', components: ['纟', '爰'], wuxing: '火', structure: '左右结构', meaning: '缓慢之象，象征缓和、从容与拖延。' },
  动: { pinyin: 'dòng', strokes: 6, radical: '力', components: ['云', '力'], wuxing: '火', structure: '左右结构', meaning: '行动之象，象征变动、活力与冲动。' },
  静: { pinyin: 'jìng', strokes: 14, radical: '青', components: ['青', '争'], wuxing: '金', structure: '左右结构', meaning: '安静之象，象征静止、沉稳与内省。' },
  升: { pinyin: 'shēng', strokes: 4, radical: '十', components: ['丿', '十'], wuxing: '金', structure: '独体字', meaning: '上升之象，象征提升、进步与发展。' },
  降: { pinyin: 'jiàng', strokes: 8, radical: '阝', components: ['阝', '夅'], wuxing: '木', structure: '左右结构', meaning: '下降之象，象征降低、收敛与退让。' },
  左: { pinyin: 'zuǒ', strokes: 5, radical: '工', components: ['一', '丿', '工'], wuxing: '火', structure: '半包围结构', meaning: '左方之象，象征辅助、次要与传统。' },
  右: { pinyin: 'yòu', strokes: 5, radical: '口', components: ['一', '丿', '口'], wuxing: '土', structure: '半包围结构', meaning: '右方之象，象征主导、重要与尊贵。' },
  前: { pinyin: 'qián', strokes: 9, radical: '刀', components: ['丷', '月', '刂'], wuxing: '金', structure: '上下结构', meaning: '前方之象，象征未来、进取与领先。' },
  后: { pinyin: 'hòu', strokes: 6, radical: '口', components: ['后'], wuxing: '水', structure: '半包围结构', meaning: '后方之象，象征过去、跟随与后盾。' },
}

export const RADICALS: Record<string, { name: string; wuxing: string }> = {
  '一': { name: '一', wuxing: '土' },
  '丨': { name: '丨', wuxing: '火' },
  '丶': { name: '丶', wuxing: '火' },
  '丿': { name: '丿', wuxing: '木' },
  '乙': { name: '乙', wuxing: '木' },
  '二': { name: '二', wuxing: '火' },
  '亠': { name: '亠', wuxing: '水' },
  '人': { name: '人', wuxing: '金' },
  '儿': { name: '儿', wuxing: '金' },
  '入': { name: '入', wuxing: '火' },
  '八': { name: '八', wuxing: '木' },
  '冂': { name: '冂', wuxing: '土' },
  '冖': { name: '冖', wuxing: '水' },
  '冫': { name: '冫', wuxing: '水' },
  '几': { name: '几', wuxing: '木' },
  '凵': { name: '凵', wuxing: '金' },
  '刀': { name: '刀', wuxing: '金' },
  '力': { name: '力', wuxing: '火' },
  '勹': { name: '勹', wuxing: '水' },
  '匕': { name: '匕', wuxing: '金' },
  '匚': { name: '匚', wuxing: '木' },
  '匸': { name: '匸', wuxing: '木' },
  '十': { name: '十', wuxing: '金' },
  '卜': { name: '卜', wuxing: '水' },
  '卩': { name: '卩', wuxing: '水' },
  '厂': { name: '厂', wuxing: '土' },
  '厶': { name: '厶', wuxing: '土' },
  '又': { name: '又', wuxing: '土' },
  '口': { name: '口', wuxing: '木' },
  '囗': { name: '囗', wuxing: '木' },
  '土': { name: '土', wuxing: '土' },
  '士': { name: '士', wuxing: '金' },
  '夂': { name: '夂', wuxing: '火' },
  '夊': { name: '夊', wuxing: '金' },
  '夕': { name: '夕', wuxing: '金' },
  '大': { name: '大', wuxing: '火' },
  '女': { name: '女', wuxing: '火' },
  '子': { name: '子', wuxing: '水' },
  '宀': { name: '宀', wuxing: '土' },
  '寸': { name: '寸', wuxing: '金' },
  '小': { name: '小', wuxing: '金' },
  '尢': { name: '尢', wuxing: '土' },
  '尸': { name: '尸', wuxing: '金' },
  '屮': { name: '屮', wuxing: '木' },
  '山': { name: '山', wuxing: '土' },
  '巛': { name: '巛', wuxing: '水' },
  '川': { name: '川', wuxing: '金' },
  '工': { name: '工', wuxing: '木' },
  '己': { name: '己', wuxing: '土' },
  '巾': { name: '巾', wuxing: '金' },
  '干': { name: '干', wuxing: '木' },
  '幺': { name: '幺', wuxing: '火' },
  '广': { name: '广', wuxing: '木' },
  '廴': { name: '廴', wuxing: '土' },
  '廾': { name: '廾', wuxing: '木' },
  '弋': { name: '弋', wuxing: '火' },
  '弓': { name: '弓', wuxing: '木' },
  '彐': { name: '彐', wuxing: '水' },
  '彡': { name: '彡', wuxing: '木' },
  '彳': { name: '彳', wuxing: '火' },
  '心': { name: '心', wuxing: '金' },
  '忄': { name: '忄', wuxing: '金' },
  '戈': { name: '戈', wuxing: '金' },
  '户': { name: '户', wuxing: '水' },
  '手': { name: '手', wuxing: '金' },
  '扌': { name: '扌', wuxing: '金' },
  '支': { name: '支', wuxing: '火' },
  '攴': { name: '攴', wuxing: '水' },
  '攵': { name: '攵', wuxing: '水' },
  '文': { name: '文', wuxing: '水' },
  '斗': { name: '斗', wuxing: '火' },
  '斤': { name: '斤', wuxing: '金' },
  '方': { name: '方', wuxing: '水' },
  '无': { name: '无', wuxing: '水' },
  '日': { name: '日', wuxing: '火' },
  '曰': { name: '曰', wuxing: '土' },
  '月': { name: '月', wuxing: '木' },
  '木': { name: '木', wuxing: '木' },
  '欠': { name: '欠', wuxing: '木' },
  '止': { name: '止', wuxing: '火' },
  '歹': { name: '歹', wuxing: '水' },
  '殳': { name: '殳', wuxing: '金' },
  '毋': { name: '毋', wuxing: '水' },
  '比': { name: '比', wuxing: '水' },
  '毛': { name: '毛', wuxing: '水' },
  '氏': { name: '氏', wuxing: '金' },
  '气': { name: '气', wuxing: '木' },
  '水': { name: '水', wuxing: '水' },
  '氵': { name: '氵', wuxing: '水' },
  '火': { name: '火', wuxing: '火' },
  '灬': { name: '灬', wuxing: '火' },
  '爪': { name: '爪', wuxing: '金' },
  '父': { name: '父', wuxing: '水' },
  '爻': { name: '爻', wuxing: '火' },
  '爿': { name: '爿', wuxing: '金' },
  '片': { name: '片', wuxing: '水' },
  '牙': { name: '牙', wuxing: '木' },
  '牛': { name: '牛', wuxing: '木' },
  '牜': { name: '牜', wuxing: '木' },
  '犬': { name: '犬', wuxing: '木' },
  '犭': { name: '犭', wuxing: '木' },
  '王': { name: '王', wuxing: '土' },
  '玉': { name: '玉', wuxing: '木' },
  '瓜': { name: '瓜', wuxing: '木' },
  '瓦': { name: '瓦', wuxing: '土' },
  '甘': { name: '甘', wuxing: '木' },
  '生': { name: '生', wuxing: '金' },
  '用': { name: '用', wuxing: '土' },
  '田': { name: '田', wuxing: '火' },
  '疋': { name: '疋', wuxing: '水' },
  '疒': { name: '疒', wuxing: '火' },
  '癶': { name: '癶', wuxing: '水' },
  '白': { name: '白', wuxing: '水' },
  '皮': { name: '皮', wuxing: '水' },
  '皿': { name: '皿', wuxing: '水' },
  '目': { name: '目', wuxing: '水' },
  '矛': { name: '矛', wuxing: '水' },
  '矢': { name: '矢', wuxing: '火' },
  '石': { name: '石', wuxing: '金' },
  '示': { name: '示', wuxing: '金' },
  '礻': { name: '礻', wuxing: '金' },
  '禸': { name: '禸', wuxing: '金' },
  '立': { name: '立', wuxing: '火' },
  '竹': { name: '竹', wuxing: '木' },
  '米': { name: '米', wuxing: '水' },
  '糸': { name: '糸', wuxing: '火' },
  '纟': { name: '纟', wuxing: '火' },
  '缶': { name: '缶', wuxing: '水' },
  '网': { name: '网', wuxing: '水' },
  '羊': { name: '羊', wuxing: '土' },
  '羽': { name: '羽', wuxing: '土' },
  '老': { name: '老', wuxing: '火' },
  '而': { name: '而', wuxing: '金' },
  '耒': { name: '耒', wuxing: '火' },
  '耳': { name: '耳', wuxing: '火' },
  '聿': { name: '聿', wuxing: '木' },
  '肉': { name: '肉', wuxing: '火' },
  '臣': { name: '臣', wuxing: '金' },
  '自': { name: '自', wuxing: '火' },
  '至': { name: '至', wuxing: '火' },
  '臼': { name: '臼', wuxing: '火' },
  '舌': { name: '舌', wuxing: '金' },
  '舛': { name: '舛', wuxing: '金' },
  '舟': { name: '舟', wuxing: '金' },
  '艮': { name: '艮', wuxing: '土' },
  '色': { name: '色', wuxing: '金' },
  '艹': { name: '艹', wuxing: '木' },
  '虍': { name: '虍', wuxing: '水' },
  '虫': { name: '虫', wuxing: '火' },
  '血': { name: '血', wuxing: '水' },
  '行': { name: '行', wuxing: '水' },
  '衣': { name: '衣', wuxing: '土' },
  '衤': { name: '衤', wuxing: '土' },
  '襾': { name: '襾', wuxing: '金' },
  '見': { name: '見', wuxing: '木' },
  '角': { name: '角', wuxing: '木' },
  '言': { name: '言', wuxing: '木' },
  '讠': { name: '讠', wuxing: '木' },
  '谷': { name: '谷', wuxing: '木' },
  '豆': { name: '豆', wuxing: '火' },
  '豕': { name: '豕', wuxing: '水' },
  '豸': { name: '豸', wuxing: '火' },
  '贝': { name: '贝', wuxing: '水' },
  '贞': { name: '贞', wuxing: '火' },
  '车': { name: '车', wuxing: '金' },
  '辶': { name: '辶', wuxing: '水' },
  '辵': { name: '辵', wuxing: '水' },
  '邑': { name: '邑', wuxing: '土' },
  '酉': { name: '酉', wuxing: '金' },
  '釆': { name: '釆', wuxing: '水' },
  '里': { name: '里', wuxing: '火' },
  '金': { name: '金', wuxing: '金' },
  '钅': { name: '钅', wuxing: '金' },
  '長': { name: '長', wuxing: '火' },
  '门': { name: '门', wuxing: '水' },
  '阜': { name: '阜', wuxing: '水' },
  '阝': { name: '阝', wuxing: '水' },
  '隹': { name: '隹', wuxing: '土' },
  '雨': { name: '雨', wuxing: '水' },
  '青': { name: '青', wuxing: '金' },
  '非': { name: '非', wuxing: '水' },
  '面': { name: '面', wuxing: '木' },
  '革': { name: '革', wuxing: '木' },
  '韦': { name: '韦', wuxing: '土' },
  '韭': { name: '韭', wuxing: '木' },
  '音': { name: '音', wuxing: '土' },
  '页': { name: '页', wuxing: '金' },
  '风': { name: '风', wuxing: '水' },
  '飞': { name: '飞', wuxing: '水' },
  '食': { name: '食', wuxing: '金' },
  '饣': { name: '饣', wuxing: '金' },
  '首': { name: '首', wuxing: '金' },
  '香': { name: '香', wuxing: '水' },
  '马': { name: '马', wuxing: '水' },
  '骨': { name: '骨', wuxing: '木' },
  '高': { name: '高', wuxing: '木' },
  '髟': { name: '髟', wuxing: '火' },
  '鬥': { name: '鬥', wuxing: '火' },
  '鬲': { name: '鬲', wuxing: '木' },
  '鬼': { name: '鬼', wuxing: '木' },
  '鱼': { name: '鱼', wuxing: '水' },
  '鸟': { name: '鸟', wuxing: '土' },
  '卤': { name: '卤', wuxing: '水' },
  '鹿': { name: '鹿', wuxing: '火' },
  '麦': { name: '麦', wuxing: '水' },
  '麻': { name: '麻', wuxing: '水' },
  '黄': { name: '黄', wuxing: '土' },
  '黍': { name: '黍', wuxing: '金' },
  '黑': { name: '黑', wuxing: '土' },
  '黹': { name: '黹', wuxing: '金' },
  '黽': { name: '黽', wuxing: '水' },
  '鼎': { name: '鼎', wuxing: '火' },
  '鼓': { name: '鼓', wuxing: '土' },
  '鼠': { name: '鼠', wuxing: '金' },
  '鼻': { name: '鼻', wuxing: '金' },
  '齊': { name: '齊', wuxing: '金' },
  '齿': { name: '齿', wuxing: '金' },
  '龙': { name: '龙', wuxing: '火' },
  '龟': { name: '龟', wuxing: '木' },
}

function isChineseChar(char: string): boolean {
  if (!char || char.length !== 1) return false
  const cp = char.codePointAt(0) || 0
  // CJK Unified Ideographs + Extension A
  return (cp >= 0x4e00 && cp <= 0x9fff) || (cp >= 0x3400 && cp <= 0x4dbf)
}

function fallbackAnalysis(char: string): CeziZhouyiCharacterAnalysis {
  const cp = char.codePointAt(0) || 0
  const strokeEstimate = 8
  let radical = '未知'
  let radicalWuxing = '土'
  for (const [r, info] of Object.entries(RADICALS)) {
    if (char.includes(r)) {
      radical = info.name
      radicalWuxing = info.wuxing
      break
    }
  }
  const wuxing = radicalWuxing
  return {
    char,
    pinyin: '（待查）',
    strokeCount: strokeEstimate,
    radical,
    components: [char],
    wuxing,
    structure: '独体字',
    meaning: `《周易》以象取义，此字 Unicode 码点为 ${cp.toString(16).toUpperCase()}，可结合所问之事观其形、音、义以断吉凶。`,
  }
}

function analyzeCharacter(char: string): CeziZhouyiCharacterAnalysis {
  const data = CHAR_DATA[char]
  if (data) {
    return {
      char,
      pinyin: data.pinyin,
      strokeCount: data.strokes,
      radical: data.radical,
      components: data.components,
      wuxing: data.wuxing,
      structure: data.structure,
      meaning: data.meaning,
    }
  }
  return fallbackAnalysis(char)
}

function deriveHexagram(strokeCount: number, codePoint: number): CeziZhouyiHexagram {
  // 梅花易数起卦法：上卦 = 笔画数 ÷ 8 取余；下卦 = (笔画数 + 码点) ÷ 8 取余；动爻 = (笔画数 + 码点 + 上卦数 + 下卦数) ÷ 6 取余
  const upperIndex = ((strokeCount - 1) % 8 + 8) % 8
  const lowerIndex = ((strokeCount + codePoint - 1) % 8 + 8) % 8
  const upper = TRIGRAMS[upperIndex]!
  const lower = TRIGRAMS[lowerIndex]!
  const hexagramKey = `${upper.name}${lower.name}`
  const movingLine = ((strokeCount + codePoint + upperIndex + lowerIndex - 1) % 6 + 6) % 6 + 1
  return {
    upperTrigram: upper.symbol,
    upperTrigramName: `${upper.name}（${upper.nature}）`,
    lowerTrigram: lower.symbol,
    lowerTrigramName: `${lower.name}（${lower.nature}）`,
    hexagram: `${upper.symbol}${lower.symbol}`,
    hexagramName: HEXAGRAM_NAMES[hexagramKey] || `${upper.name}${lower.name}`,
    movingLine,
  }
}

export function calculateCeziZhouyi(payload: CeziZhouyiRequest): CeziZhouyiResult {
  const char = payload.char?.trim()
  if (!char || !isChineseChar(char)) {
    throw new Error('请输入一个汉字')
  }
  if (!payload.question || payload.question.trim().length === 0) {
    throw new Error('请填写所问事项')
  }

  const analysis = analyzeCharacter(char)
  const codePoint = char.codePointAt(0) || 0
  const hexagram = deriveHexagram(analysis.strokeCount, codePoint)

  return {
    input: {
      char,
      question: payload.question.trim(),
      gender: payload.gender ?? null,
      birthYear: payload.birthYear ?? null,
    },
    analysis,
    hexagram,
  }
}

export { isChineseChar }
